package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.ApecActividadesTres;
import mx.gob.sep.dgtec.repuce.model.ApecActividadesTresExample;
import org.apache.ibatis.annotations.Param;

public interface ApecActividadesTresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_tres
     *
     * @mbggenerated Mon Jul 09 14:32:33 CDT 2018
     */
    int countByExample(ApecActividadesTresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_tres
     *
     * @mbggenerated Mon Jul 09 14:32:33 CDT 2018
     */
    int deleteByExample(ApecActividadesTresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_tres
     *
     * @mbggenerated Mon Jul 09 14:32:33 CDT 2018
     */
    int deleteByPrimaryKey(@Param("cApec") Integer cApec, @Param("cReunion") Short cReunion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_tres
     *
     * @mbggenerated Mon Jul 09 14:32:33 CDT 2018
     */
    int insert(ApecActividadesTres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_tres
     *
     * @mbggenerated Mon Jul 09 14:32:33 CDT 2018
     */
    int insertSelective(ApecActividadesTres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_tres
     *
     * @mbggenerated Mon Jul 09 14:32:33 CDT 2018
     */
    List<ApecActividadesTres> selectByExample(ApecActividadesTresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_tres
     *
     * @mbggenerated Mon Jul 09 14:32:33 CDT 2018
     */
    ApecActividadesTres selectByPrimaryKey(@Param("cApec") Integer cApec, @Param("cReunion") Short cReunion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_tres
     *
     * @mbggenerated Mon Jul 09 14:32:33 CDT 2018
     */
    int updateByExampleSelective(@Param("record") ApecActividadesTres record, @Param("example") ApecActividadesTresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_tres
     *
     * @mbggenerated Mon Jul 09 14:32:33 CDT 2018
     */
    int updateByExample(@Param("record") ApecActividadesTres record, @Param("example") ApecActividadesTresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_tres
     *
     * @mbggenerated Mon Jul 09 14:32:33 CDT 2018
     */
    int updateByPrimaryKeySelective(ApecActividadesTres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_tres
     *
     * @mbggenerated Mon Jul 09 14:32:33 CDT 2018
     */
    int updateByPrimaryKey(ApecActividadesTres record);
}