package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.ApecEncuestaSatisfaccion;
import mx.gob.sep.dgtec.repuce.model.ApecEncuestaSatisfaccionExample;
import org.apache.ibatis.annotations.Param;

public interface ApecEncuestaSatisfaccionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_encuesta_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int countByExample(ApecEncuestaSatisfaccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_encuesta_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int deleteByExample(ApecEncuestaSatisfaccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_encuesta_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int deleteByPrimaryKey(@Param("cApec") Integer cApec, @Param("cReunion") Short cReunion, @Param("cMedicionSatisfaccion") Integer cMedicionSatisfaccion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_encuesta_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int insert(ApecEncuestaSatisfaccion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_encuesta_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int insertSelective(ApecEncuestaSatisfaccion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_encuesta_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    List<ApecEncuestaSatisfaccion> selectByExample(ApecEncuestaSatisfaccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_encuesta_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    ApecEncuestaSatisfaccion selectByPrimaryKey(@Param("cApec") Integer cApec, @Param("cReunion") Short cReunion, @Param("cMedicionSatisfaccion") Integer cMedicionSatisfaccion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_encuesta_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByExampleSelective(@Param("record") ApecEncuestaSatisfaccion record, @Param("example") ApecEncuestaSatisfaccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_encuesta_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByExample(@Param("record") ApecEncuestaSatisfaccion record, @Param("example") ApecEncuestaSatisfaccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_encuesta_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByPrimaryKeySelective(ApecEncuestaSatisfaccion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_encuesta_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByPrimaryKey(ApecEncuestaSatisfaccion record);
}