package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.ApecActividadesUno;
import mx.gob.sep.dgtec.repuce.model.ApecActividadesUnoExample;
import org.apache.ibatis.annotations.Param;

public interface ApecActividadesUnoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_uno
     *
     * @mbggenerated Mon Sep 03 16:33:32 CDT 2018
     */
    int countByExample(ApecActividadesUnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_uno
     *
     * @mbggenerated Mon Sep 03 16:33:32 CDT 2018
     */
    int deleteByExample(ApecActividadesUnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_uno
     *
     * @mbggenerated Mon Sep 03 16:33:32 CDT 2018
     */
    int deleteByPrimaryKey(@Param("cApec") Integer cApec, @Param("cReunion") Short cReunion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_uno
     *
     * @mbggenerated Mon Sep 03 16:33:32 CDT 2018
     */
    int insert(ApecActividadesUno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_uno
     *
     * @mbggenerated Mon Sep 03 16:33:32 CDT 2018
     */
    int insertSelective(ApecActividadesUno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_uno
     *
     * @mbggenerated Mon Sep 03 16:33:32 CDT 2018
     */
    List<ApecActividadesUno> selectByExample(ApecActividadesUnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_uno
     *
     * @mbggenerated Mon Sep 03 16:33:32 CDT 2018
     */
    ApecActividadesUno selectByPrimaryKey(@Param("cApec") Integer cApec, @Param("cReunion") Short cReunion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_uno
     *
     * @mbggenerated Mon Sep 03 16:33:32 CDT 2018
     */
    int updateByExampleSelective(@Param("record") ApecActividadesUno record, @Param("example") ApecActividadesUnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_uno
     *
     * @mbggenerated Mon Sep 03 16:33:32 CDT 2018
     */
    int updateByExample(@Param("record") ApecActividadesUno record, @Param("example") ApecActividadesUnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_uno
     *
     * @mbggenerated Mon Sep 03 16:33:32 CDT 2018
     */
    int updateByPrimaryKeySelective(ApecActividadesUno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_actividades_uno
     *
     * @mbggenerated Mon Sep 03 16:33:32 CDT 2018
     */
    int updateByPrimaryKey(ApecActividadesUno record);
}