package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.ApecApoyo;
import mx.gob.sep.dgtec.repuce.model.ApecApoyoExample;
import org.apache.ibatis.annotations.Param;

public interface ApecApoyoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_apoyo
     *
     * @mbggenerated Thu May 18 17:51:17 CDT 2017
     */
    int countByExample(ApecApoyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_apoyo
     *
     * @mbggenerated Thu May 18 17:51:17 CDT 2017
     */
    int deleteByExample(ApecApoyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_apoyo
     *
     * @mbggenerated Thu May 18 17:51:17 CDT 2017
     */
    int deleteByPrimaryKey(@Param("cApec") Integer cApec, @Param("cReunion") Short cReunion, @Param("cApoyo") Integer cApoyo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_apoyo
     *
     * @mbggenerated Thu May 18 17:51:17 CDT 2017
     */
    int insert(ApecApoyo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_apoyo
     *
     * @mbggenerated Thu May 18 17:51:17 CDT 2017
     */
    int insertSelective(ApecApoyo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_apoyo
     *
     * @mbggenerated Thu May 18 17:51:17 CDT 2017
     */
    List<ApecApoyo> selectByExample(ApecApoyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_apoyo
     *
     * @mbggenerated Thu May 18 17:51:17 CDT 2017
     */
    ApecApoyo selectByPrimaryKey(@Param("cApec") Integer cApec, @Param("cReunion") Short cReunion, @Param("cApoyo") Integer cApoyo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_apoyo
     *
     * @mbggenerated Thu May 18 17:51:17 CDT 2017
     */
    int updateByExampleSelective(@Param("record") ApecApoyo record, @Param("example") ApecApoyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_apoyo
     *
     * @mbggenerated Thu May 18 17:51:17 CDT 2017
     */
    int updateByExample(@Param("record") ApecApoyo record, @Param("example") ApecApoyoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_apoyo
     *
     * @mbggenerated Thu May 18 17:51:17 CDT 2017
     */
    int updateByPrimaryKeySelective(ApecApoyo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_apoyo
     *
     * @mbggenerated Thu May 18 17:51:17 CDT 2017
     */
    int updateByPrimaryKey(ApecApoyo record);
}