package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.ApecReunionInstructor;
import mx.gob.sep.dgtec.repuce.model.ApecReunionInstructorExample;
import org.apache.ibatis.annotations.Param;

public interface ApecReunionInstructorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_reunion_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int countByExample(ApecReunionInstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_reunion_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int deleteByExample(ApecReunionInstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_reunion_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int deleteByPrimaryKey(@Param("cApec") Integer cApec, @Param("cReunion") Short cReunion, @Param("cApecInstructor") Integer cApecInstructor, @Param("cInstructor") Short cInstructor);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_reunion_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int insert(ApecReunionInstructor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_reunion_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int insertSelective(ApecReunionInstructor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_reunion_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    List<ApecReunionInstructor> selectByExample(ApecReunionInstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_reunion_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int updateByExampleSelective(@Param("record") ApecReunionInstructor record, @Param("example") ApecReunionInstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_reunion_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int updateByExample(@Param("record") ApecReunionInstructor record, @Param("example") ApecReunionInstructorExample example);
}