package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CCalidadInt;
import mx.gob.sep.dgtec.repuce.model.CCalidadIntExample;
import org.apache.ibatis.annotations.Param;

public interface CCalidadIntMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int countByExample(CCalidadIntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int deleteByExample(CCalidadIntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int deleteByPrimaryKey(Integer cCalidad);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int insert(CCalidadInt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int insertSelective(CCalidadInt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    List<CCalidadInt> selectByExample(CCalidadIntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    CCalidadInt selectByPrimaryKey(Integer cCalidad);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByExampleSelective(@Param("record") CCalidadInt record, @Param("example") CCalidadIntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByExample(@Param("record") CCalidadInt record, @Param("example") CCalidadIntExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByPrimaryKeySelective(CCalidadInt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByPrimaryKey(CCalidadInt record);
}