package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CCctInstructor;
import mx.gob.sep.dgtec.repuce.model.CCctInstructorExample;
import org.apache.ibatis.annotations.Param;

public interface CCctInstructorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cct_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int countByExample(CCctInstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cct_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int deleteByExample(CCctInstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cct_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int insert(CCctInstructor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cct_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int insertSelective(CCctInstructor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cct_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    List<CCctInstructor> selectByExample(CCctInstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cct_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int updateByExampleSelective(@Param("record") CCctInstructor record, @Param("example") CCctInstructorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_cct_instructor
     *
     * @mbggenerated Thu Dec 12 14:51:34 CST 2013
     */
    int updateByExample(@Param("record") CCctInstructor record, @Param("example") CCctInstructorExample example);
}