package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CDiferenciaPgr;
import mx.gob.sep.dgtec.repuce.model.CDiferenciaPgrExample;
import org.apache.ibatis.annotations.Param;

public interface CDiferenciaPgrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_diferencia_pgr
     *
     * @mbggenerated Wed Jan 23 19:09:12 CST 2013
     */
    int countByExample(CDiferenciaPgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_diferencia_pgr
     *
     * @mbggenerated Wed Jan 23 19:09:12 CST 2013
     */
    int deleteByExample(CDiferenciaPgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_diferencia_pgr
     *
     * @mbggenerated Wed Jan 23 19:09:12 CST 2013
     */
    int deleteByPrimaryKey(Short cDiferencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_diferencia_pgr
     *
     * @mbggenerated Wed Jan 23 19:09:12 CST 2013
     */
    int insert(CDiferenciaPgr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_diferencia_pgr
     *
     * @mbggenerated Wed Jan 23 19:09:12 CST 2013
     */
    int insertSelective(CDiferenciaPgr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_diferencia_pgr
     *
     * @mbggenerated Wed Jan 23 19:09:12 CST 2013
     */
    List<CDiferenciaPgr> selectByExample(CDiferenciaPgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_diferencia_pgr
     *
     * @mbggenerated Wed Jan 23 19:09:12 CST 2013
     */
    CDiferenciaPgr selectByPrimaryKey(Short cDiferencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_diferencia_pgr
     *
     * @mbggenerated Wed Jan 23 19:09:12 CST 2013
     */
    int updateByExampleSelective(@Param("record") CDiferenciaPgr record, @Param("example") CDiferenciaPgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_diferencia_pgr
     *
     * @mbggenerated Wed Jan 23 19:09:12 CST 2013
     */
    int updateByExample(@Param("record") CDiferenciaPgr record, @Param("example") CDiferenciaPgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_diferencia_pgr
     *
     * @mbggenerated Wed Jan 23 19:09:12 CST 2013
     */
    int updateByPrimaryKeySelective(CDiferenciaPgr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_diferencia_pgr
     *
     * @mbggenerated Wed Jan 23 19:09:12 CST 2013
     */
    int updateByPrimaryKey(CDiferenciaPgr record);
}