package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CeComitesSeguimiento;
import mx.gob.sep.dgtec.repuce.model.CeComitesSeguimientoExample;
import org.apache.ibatis.annotations.Param;

public interface CeComitesSeguimientoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    int countByExample(CeComitesSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    int deleteByExample(CeComitesSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    int deleteByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("idComite") Integer idComite);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    int insert(CeComitesSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    int insertSelective(CeComitesSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    List<CeComitesSeguimiento> selectByExample(CeComitesSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    CeComitesSeguimiento selectByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("idComite") Integer idComite);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    int updateByExampleSelective(@Param("record") CeComitesSeguimiento record, @Param("example") CeComitesSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    int updateByExample(@Param("record") CeComitesSeguimiento record, @Param("example") CeComitesSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    int updateByPrimaryKeySelective(CeComitesSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    int updateByPrimaryKey(CeComitesSeguimiento record);
}