package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CeIntegranteComite;
import mx.gob.sep.dgtec.repuce.model.CeIntegranteComiteExample;
import org.apache.ibatis.annotations.Param;

public interface CeIntegranteComiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_comite
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int countByExample(CeIntegranteComiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_comite
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int deleteByExample(CeIntegranteComiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_comite
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int deleteByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("cscIntegrante") Short cscIntegrante);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_comite
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int insert(CeIntegranteComite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_comite
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int insertSelective(CeIntegranteComite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_comite
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    List<CeIntegranteComite> selectByExample(CeIntegranteComiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_comite
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    CeIntegranteComite selectByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("cscIntegrante") Short cscIntegrante);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_comite
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByExampleSelective(@Param("record") CeIntegranteComite record, @Param("example") CeIntegranteComiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_comite
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByExample(@Param("record") CeIntegranteComite record, @Param("example") CeIntegranteComiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_comite
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByPrimaryKeySelective(CeIntegranteComite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_comite
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByPrimaryKey(CeIntegranteComite record);
}