package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CeIntegrante;
import mx.gob.sep.dgtec.repuce.model.CeIntegranteExample;
import org.apache.ibatis.annotations.Param;

public interface CeIntegranteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante
     *
     * @mbggenerated Tue Aug 11 12:43:36 CDT 2015
     */
    int countByExample(CeIntegranteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante
     *
     * @mbggenerated Tue Aug 11 12:43:36 CDT 2015
     */
    int deleteByExample(CeIntegranteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante
     *
     * @mbggenerated Tue Aug 11 12:43:36 CDT 2015
     */
    int deleteByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("cscIntegrante") Short cscIntegrante);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante
     *
     * @mbggenerated Tue Aug 11 12:43:36 CDT 2015
     */
    int insert(CeIntegrante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante
     *
     * @mbggenerated Tue Aug 11 12:43:36 CDT 2015
     */
    int insertSelective(CeIntegrante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante
     *
     * @mbggenerated Tue Aug 11 12:43:36 CDT 2015
     */
    List<CeIntegrante> selectByExample(CeIntegranteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante
     *
     * @mbggenerated Tue Aug 11 12:43:36 CDT 2015
     */
    CeIntegrante selectByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("cscIntegrante") Short cscIntegrante);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante
     *
     * @mbggenerated Tue Aug 11 12:43:36 CDT 2015
     */
    int updateByExampleSelective(@Param("record") CeIntegrante record, @Param("example") CeIntegranteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante
     *
     * @mbggenerated Tue Aug 11 12:43:36 CDT 2015
     */
    int updateByExample(@Param("record") CeIntegrante record, @Param("example") CeIntegranteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante
     *
     * @mbggenerated Tue Aug 11 12:43:36 CDT 2015
     */
    int updateByPrimaryKeySelective(CeIntegrante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante
     *
     * @mbggenerated Tue Aug 11 12:43:36 CDT 2015
     */
    int updateByPrimaryKey(CeIntegrante record);
}