package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CeIntegranteMesa;
import mx.gob.sep.dgtec.repuce.model.CeIntegranteMesaExample;
import org.apache.ibatis.annotations.Param;

public interface CeIntegranteMesaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_mesa
     *
     * @mbggenerated Thu Oct 17 11:44:43 CDT 2013
     */
    int countByExample(CeIntegranteMesaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_mesa
     *
     * @mbggenerated Thu Oct 17 11:44:43 CDT 2013
     */
    int deleteByExample(CeIntegranteMesaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_mesa
     *
     * @mbggenerated Thu Oct 17 11:44:43 CDT 2013
     */
    int deleteByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("idIntegrante") Short idIntegrante);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_mesa
     *
     * @mbggenerated Thu Oct 17 11:44:43 CDT 2013
     */
    int insert(CeIntegranteMesa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_mesa
     *
     * @mbggenerated Thu Oct 17 11:44:43 CDT 2013
     */
    int insertSelective(CeIntegranteMesa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_mesa
     *
     * @mbggenerated Thu Oct 17 11:44:43 CDT 2013
     */
    List<CeIntegranteMesa> selectByExample(CeIntegranteMesaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_mesa
     *
     * @mbggenerated Thu Oct 17 11:44:43 CDT 2013
     */
    CeIntegranteMesa selectByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("idIntegrante") Short idIntegrante);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_mesa
     *
     * @mbggenerated Thu Oct 17 11:44:43 CDT 2013
     */
    int updateByExampleSelective(@Param("record") CeIntegranteMesa record, @Param("example") CeIntegranteMesaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_mesa
     *
     * @mbggenerated Thu Oct 17 11:44:43 CDT 2013
     */
    int updateByExample(@Param("record") CeIntegranteMesa record, @Param("example") CeIntegranteMesaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_mesa
     *
     * @mbggenerated Thu Oct 17 11:44:43 CDT 2013
     */
    int updateByPrimaryKeySelective(CeIntegranteMesa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_mesa
     *
     * @mbggenerated Thu Oct 17 11:44:43 CDT 2013
     */
    int updateByPrimaryKey(CeIntegranteMesa record);
}