package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CEntidad;
import mx.gob.sep.dgtec.repuce.model.CEntidadExample;
import org.apache.ibatis.annotations.Param;

public interface CEntidadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int countByExample(CEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int deleteByExample(CEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int deleteByPrimaryKey(Short idEntidadfed);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int insert(CEntidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int insertSelective(CEntidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    List<CEntidad> selectByExample(CEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    CEntidad selectByPrimaryKey(Short idEntidadfed);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByExampleSelective(@Param("record") CEntidad record, @Param("example") CEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByExample(@Param("record") CEntidad record, @Param("example") CEntidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByPrimaryKeySelective(CEntidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByPrimaryKey(CEntidad record);
}