package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CePlaneacion;
import mx.gob.sep.dgtec.repuce.model.CePlaneacionExample;
import org.apache.ibatis.annotations.Param;

public interface CePlaneacionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_planeacion
     *
     * @mbggenerated Thu Feb 07 17:28:07 CST 2013
     */
    int countByExample(CePlaneacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_planeacion
     *
     * @mbggenerated Thu Feb 07 17:28:07 CST 2013
     */
    int deleteByExample(CePlaneacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_planeacion
     *
     * @mbggenerated Thu Feb 07 17:28:07 CST 2013
     */
    int deleteByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_planeacion
     *
     * @mbggenerated Thu Feb 07 17:28:07 CST 2013
     */
    int insert(CePlaneacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_planeacion
     *
     * @mbggenerated Thu Feb 07 17:28:07 CST 2013
     */
    int insertSelective(CePlaneacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_planeacion
     *
     * @mbggenerated Thu Feb 07 17:28:07 CST 2013
     */
    List<CePlaneacion> selectByExample(CePlaneacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_planeacion
     *
     * @mbggenerated Thu Feb 07 17:28:07 CST 2013
     */
    CePlaneacion selectByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_planeacion
     *
     * @mbggenerated Thu Feb 07 17:28:07 CST 2013
     */
    int updateByExampleSelective(@Param("record") CePlaneacion record, @Param("example") CePlaneacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_planeacion
     *
     * @mbggenerated Thu Feb 07 17:28:07 CST 2013
     */
    int updateByExample(@Param("record") CePlaneacion record, @Param("example") CePlaneacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_planeacion
     *
     * @mbggenerated Thu Feb 07 17:28:07 CST 2013
     */
    int updateByPrimaryKeySelective(CePlaneacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_planeacion
     *
     * @mbggenerated Thu Feb 07 17:28:07 CST 2013
     */
    int updateByPrimaryKey(CePlaneacion record);
}