package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CePreguntasMunicipal;
import mx.gob.sep.dgtec.repuce.model.CePreguntasMunicipalExample;
import org.apache.ibatis.annotations.Param;

public interface CePreguntasMunicipalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_preguntas_municipal
     *
     * @mbggenerated Mon Jun 01 19:03:36 CDT 2015
     */
    int countByExample(CePreguntasMunicipalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_preguntas_municipal
     *
     * @mbggenerated Mon Jun 01 19:03:36 CDT 2015
     */
    int deleteByExample(CePreguntasMunicipalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_preguntas_municipal
     *
     * @mbggenerated Mon Jun 01 19:03:36 CDT 2015
     */
    int deleteByPrimaryKey(@Param("cctId") Integer cctId, @Param("cSesion") Short cSesion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_preguntas_municipal
     *
     * @mbggenerated Mon Jun 01 19:03:36 CDT 2015
     */
    int insert(CePreguntasMunicipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_preguntas_municipal
     *
     * @mbggenerated Mon Jun 01 19:03:36 CDT 2015
     */
    int insertSelective(CePreguntasMunicipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_preguntas_municipal
     *
     * @mbggenerated Mon Jun 01 19:03:36 CDT 2015
     */
    List<CePreguntasMunicipal> selectByExample(CePreguntasMunicipalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_preguntas_municipal
     *
     * @mbggenerated Mon Jun 01 19:03:36 CDT 2015
     */
    CePreguntasMunicipal selectByPrimaryKey(@Param("cctId") Integer cctId, @Param("cSesion") Short cSesion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_preguntas_municipal
     *
     * @mbggenerated Mon Jun 01 19:03:36 CDT 2015
     */
    int updateByExampleSelective(@Param("record") CePreguntasMunicipal record, @Param("example") CePreguntasMunicipalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_preguntas_municipal
     *
     * @mbggenerated Mon Jun 01 19:03:36 CDT 2015
     */
    int updateByExample(@Param("record") CePreguntasMunicipal record, @Param("example") CePreguntasMunicipalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_preguntas_municipal
     *
     * @mbggenerated Mon Jun 01 19:03:36 CDT 2015
     */
    int updateByPrimaryKeySelective(CePreguntasMunicipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_preguntas_municipal
     *
     * @mbggenerated Mon Jun 01 19:03:36 CDT 2015
     */
    int updateByPrimaryKey(CePreguntasMunicipal record);
}