package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CeProgramaComite;
import mx.gob.sep.dgtec.repuce.model.CeProgramaComiteExample;
import org.apache.ibatis.annotations.Param;

public interface CeProgramaComiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_programa_comite
     *
     * @mbggenerated Wed Apr 20 11:35:12 CDT 2016
     */
    int countByExample(CeProgramaComiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_programa_comite
     *
     * @mbggenerated Wed Apr 20 11:35:12 CDT 2016
     */
    int deleteByExample(CeProgramaComiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_programa_comite
     *
     * @mbggenerated Wed Apr 20 11:35:12 CDT 2016
     */
    int deleteByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("cProgramaComite") Short cProgramaComite);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_programa_comite
     *
     * @mbggenerated Wed Apr 20 11:35:12 CDT 2016
     */
    int insert(CeProgramaComite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_programa_comite
     *
     * @mbggenerated Wed Apr 20 11:35:12 CDT 2016
     */
    int insertSelective(CeProgramaComite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_programa_comite
     *
     * @mbggenerated Wed Apr 20 11:35:12 CDT 2016
     */
    List<CeProgramaComite> selectByExample(CeProgramaComiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_programa_comite
     *
     * @mbggenerated Wed Apr 20 11:35:12 CDT 2016
     */
    CeProgramaComite selectByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("cProgramaComite") Short cProgramaComite);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_programa_comite
     *
     * @mbggenerated Wed Apr 20 11:35:12 CDT 2016
     */
    int updateByExampleSelective(@Param("record") CeProgramaComite record, @Param("example") CeProgramaComiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_programa_comite
     *
     * @mbggenerated Wed Apr 20 11:35:12 CDT 2016
     */
    int updateByExample(@Param("record") CeProgramaComite record, @Param("example") CeProgramaComiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_programa_comite
     *
     * @mbggenerated Wed Apr 20 11:35:12 CDT 2016
     */
    int updateByPrimaryKeySelective(CeProgramaComite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_programa_comite
     *
     * @mbggenerated Wed Apr 20 11:35:12 CDT 2016
     */
    int updateByPrimaryKey(CeProgramaComite record);
}