package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CePreguntaRecursosPadres;
import mx.gob.sep.dgtec.repuce.model.CePreguntaRecursosPadresExample;
import org.apache.ibatis.annotations.Param;

public interface CePreguntaRecursosPadresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_pregunta_recursos_padres
     *
     * @mbggenerated Tue Jun 02 11:31:23 CDT 2015
     */
    int countByExample(CePreguntaRecursosPadresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_pregunta_recursos_padres
     *
     * @mbggenerated Tue Jun 02 11:31:23 CDT 2015
     */
    int deleteByExample(CePreguntaRecursosPadresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_pregunta_recursos_padres
     *
     * @mbggenerated Tue Jun 02 11:31:23 CDT 2015
     */
    int deleteByPrimaryKey(@Param("cctId") Integer cctId, @Param("cSesion") Short cSesion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_pregunta_recursos_padres
     *
     * @mbggenerated Tue Jun 02 11:31:23 CDT 2015
     */
    int insert(CePreguntaRecursosPadres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_pregunta_recursos_padres
     *
     * @mbggenerated Tue Jun 02 11:31:23 CDT 2015
     */
    int insertSelective(CePreguntaRecursosPadres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_pregunta_recursos_padres
     *
     * @mbggenerated Tue Jun 02 11:31:23 CDT 2015
     */
    List<CePreguntaRecursosPadres> selectByExample(CePreguntaRecursosPadresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_pregunta_recursos_padres
     *
     * @mbggenerated Tue Jun 02 11:31:23 CDT 2015
     */
    CePreguntaRecursosPadres selectByPrimaryKey(@Param("cctId") Integer cctId, @Param("cSesion") Short cSesion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_pregunta_recursos_padres
     *
     * @mbggenerated Tue Jun 02 11:31:23 CDT 2015
     */
    int updateByExampleSelective(@Param("record") CePreguntaRecursosPadres record, @Param("example") CePreguntaRecursosPadresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_pregunta_recursos_padres
     *
     * @mbggenerated Tue Jun 02 11:31:23 CDT 2015
     */
    int updateByExample(@Param("record") CePreguntaRecursosPadres record, @Param("example") CePreguntaRecursosPadresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_pregunta_recursos_padres
     *
     * @mbggenerated Tue Jun 02 11:31:23 CDT 2015
     */
    int updateByPrimaryKeySelective(CePreguntaRecursosPadres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_pregunta_recursos_padres
     *
     * @mbggenerated Tue Jun 02 11:31:23 CDT 2015
     */
    int updateByPrimaryKey(CePreguntaRecursosPadres record);
}