package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CeRecurso;
import mx.gob.sep.dgtec.repuce.model.CeRecursoExample;
import org.apache.ibatis.annotations.Param;

public interface CeRecursoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recurso
     *
     * @mbggenerated Thu Feb 07 13:17:28 CST 2013
     */
    int countByExample(CeRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recurso
     *
     * @mbggenerated Thu Feb 07 13:17:28 CST 2013
     */
    int deleteByExample(CeRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recurso
     *
     * @mbggenerated Thu Feb 07 13:17:28 CST 2013
     */
    int deleteByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("cRecurso") Short cRecurso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recurso
     *
     * @mbggenerated Thu Feb 07 13:17:28 CST 2013
     */
    int insert(CeRecurso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recurso
     *
     * @mbggenerated Thu Feb 07 13:17:28 CST 2013
     */
    int insertSelective(CeRecurso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recurso
     *
     * @mbggenerated Thu Feb 07 13:17:28 CST 2013
     */
    List<CeRecurso> selectByExample(CeRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recurso
     *
     * @mbggenerated Thu Feb 07 13:17:28 CST 2013
     */
    CeRecurso selectByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion, @Param("cRecurso") Short cRecurso);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recurso
     *
     * @mbggenerated Thu Feb 07 13:17:28 CST 2013
     */
    int updateByExampleSelective(@Param("record") CeRecurso record, @Param("example") CeRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recurso
     *
     * @mbggenerated Thu Feb 07 13:17:28 CST 2013
     */
    int updateByExample(@Param("record") CeRecurso record, @Param("example") CeRecursoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recurso
     *
     * @mbggenerated Thu Feb 07 13:17:28 CST 2013
     */
    int updateByPrimaryKeySelective(CeRecurso record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recurso
     *
     * @mbggenerated Thu Feb 07 13:17:28 CST 2013
     */
    int updateByPrimaryKey(CeRecurso record);
}