package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CLengua;
import mx.gob.sep.dgtec.repuce.model.CLenguaExample;
import org.apache.ibatis.annotations.Param;

public interface CLenguaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_lengua
     *
     * @mbggenerated Fri Oct 18 11:03:43 CDT 2013
     */
    int countByExample(CLenguaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_lengua
     *
     * @mbggenerated Fri Oct 18 11:03:43 CDT 2013
     */
    int deleteByExample(CLenguaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_lengua
     *
     * @mbggenerated Fri Oct 18 11:03:43 CDT 2013
     */
    int deleteByPrimaryKey(Integer cLengua);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_lengua
     *
     * @mbggenerated Fri Oct 18 11:03:43 CDT 2013
     */
    int insert(CLengua record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_lengua
     *
     * @mbggenerated Fri Oct 18 11:03:43 CDT 2013
     */
    int insertSelective(CLengua record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_lengua
     *
     * @mbggenerated Fri Oct 18 11:03:43 CDT 2013
     */
    List<CLengua> selectByExample(CLenguaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_lengua
     *
     * @mbggenerated Fri Oct 18 11:03:43 CDT 2013
     */
    CLengua selectByPrimaryKey(Integer cLengua);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_lengua
     *
     * @mbggenerated Fri Oct 18 11:03:43 CDT 2013
     */
    int updateByExampleSelective(@Param("record") CLengua record, @Param("example") CLenguaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_lengua
     *
     * @mbggenerated Fri Oct 18 11:03:43 CDT 2013
     */
    int updateByExample(@Param("record") CLengua record, @Param("example") CLenguaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_lengua
     *
     * @mbggenerated Fri Oct 18 11:03:43 CDT 2013
     */
    int updateByPrimaryKeySelective(CLengua record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_lengua
     *
     * @mbggenerated Fri Oct 18 11:03:43 CDT 2013
     */
    int updateByPrimaryKey(CLengua record);
}