package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CLocalidad;
import mx.gob.sep.dgtec.repuce.model.CLocalidadExample;
import org.apache.ibatis.annotations.Param;

public interface CLocalidadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int countByExample(CLocalidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int deleteByExample(CLocalidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int deleteByPrimaryKey(@Param("idLocalidad") Integer idLocalidad, @Param("idMunicipio") Integer idMunicipio, @Param("idEntidadfed") Short idEntidadfed);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int insert(CLocalidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int insertSelective(CLocalidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    List<CLocalidad> selectByExample(CLocalidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    CLocalidad selectByPrimaryKey(@Param("idLocalidad") Integer idLocalidad, @Param("idMunicipio") Integer idMunicipio, @Param("idEntidadfed") Short idEntidadfed);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByExampleSelective(@Param("record") CLocalidad record, @Param("example") CLocalidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByExample(@Param("record") CLocalidad record, @Param("example") CLocalidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByPrimaryKeySelective(CLocalidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    int updateByPrimaryKey(CLocalidad record);
}