package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CMedicionSatisfaccion;
import mx.gob.sep.dgtec.repuce.model.CMedicionSatisfaccionExample;
import org.apache.ibatis.annotations.Param;

public interface CMedicionSatisfaccionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_medicion_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int countByExample(CMedicionSatisfaccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_medicion_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int deleteByExample(CMedicionSatisfaccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_medicion_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int deleteByPrimaryKey(Integer cMedicionSatisfaccion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_medicion_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int insert(CMedicionSatisfaccion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_medicion_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int insertSelective(CMedicionSatisfaccion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_medicion_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    List<CMedicionSatisfaccion> selectByExample(CMedicionSatisfaccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_medicion_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    CMedicionSatisfaccion selectByPrimaryKey(Integer cMedicionSatisfaccion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_medicion_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByExampleSelective(@Param("record") CMedicionSatisfaccion record, @Param("example") CMedicionSatisfaccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_medicion_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByExample(@Param("record") CMedicionSatisfaccion record, @Param("example") CMedicionSatisfaccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_medicion_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByPrimaryKeySelective(CMedicionSatisfaccion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_medicion_satisfaccion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByPrimaryKey(CMedicionSatisfaccion record);
}