package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CmSeguimiento;
import mx.gob.sep.dgtec.repuce.model.CmSeguimientoExample;
import org.apache.ibatis.annotations.Param;

public interface CmSeguimientoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_seguimiento
     *
     * @mbggenerated Thu Jan 10 18:58:18 CST 2013
     */
    int countByExample(CmSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_seguimiento
     *
     * @mbggenerated Thu Jan 10 18:58:18 CST 2013
     */
    int deleteByExample(CmSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_seguimiento
     *
     * @mbggenerated Thu Jan 10 18:58:18 CST 2013
     */
    int deleteByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_seguimiento
     *
     * @mbggenerated Thu Jan 10 18:58:18 CST 2013
     */
    int insert(CmSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_seguimiento
     *
     * @mbggenerated Thu Jan 10 18:58:18 CST 2013
     */
    int insertSelective(CmSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_seguimiento
     *
     * @mbggenerated Thu Jan 10 18:58:18 CST 2013
     */
    List<CmSeguimiento> selectByExample(CmSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_seguimiento
     *
     * @mbggenerated Thu Jan 10 18:58:18 CST 2013
     */
    CmSeguimiento selectByPrimaryKey(@Param("cCct") Integer cCct, @Param("cSesion") Short cSesion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_seguimiento
     *
     * @mbggenerated Thu Jan 10 18:58:18 CST 2013
     */
    int updateByExampleSelective(@Param("record") CmSeguimiento record, @Param("example") CmSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_seguimiento
     *
     * @mbggenerated Thu Jan 10 18:58:18 CST 2013
     */
    int updateByExample(@Param("record") CmSeguimiento record, @Param("example") CmSeguimientoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_seguimiento
     *
     * @mbggenerated Thu Jan 10 18:58:18 CST 2013
     */
    int updateByPrimaryKeySelective(CmSeguimiento record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_seguimiento
     *
     * @mbggenerated Thu Jan 10 18:58:18 CST 2013
     */
    int updateByPrimaryKey(CmSeguimiento record);
}