package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CNormalidad;
import mx.gob.sep.dgtec.repuce.model.CNormalidadExample;
import org.apache.ibatis.annotations.Param;

public interface CNormalidadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_normalidad
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    int countByExample(CNormalidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_normalidad
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    int deleteByExample(CNormalidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_normalidad
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    int deleteByPrimaryKey(Integer cNormalidad);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_normalidad
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    int insert(CNormalidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_normalidad
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    int insertSelective(CNormalidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_normalidad
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    List<CNormalidad> selectByExample(CNormalidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_normalidad
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    CNormalidad selectByPrimaryKey(Integer cNormalidad);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_normalidad
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    int updateByExampleSelective(@Param("record") CNormalidad record, @Param("example") CNormalidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_normalidad
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    int updateByExample(@Param("record") CNormalidad record, @Param("example") CNormalidadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_normalidad
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    int updateByPrimaryKeySelective(CNormalidad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_normalidad
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    int updateByPrimaryKey(CNormalidad record);
}