package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.ConsejoMun1415;
import mx.gob.sep.dgtec.repuce.model.ConsejoMun1415Example;
import org.apache.ibatis.annotations.Param;

public interface ConsejoMun1415Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consejo_mun1415
     *
     * @mbggenerated Wed Feb 11 12:01:48 CST 2015
     */
    int countByExample(ConsejoMun1415Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consejo_mun1415
     *
     * @mbggenerated Wed Feb 11 12:01:48 CST 2015
     */
    int deleteByExample(ConsejoMun1415Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consejo_mun1415
     *
     * @mbggenerated Wed Feb 11 12:01:48 CST 2015
     */
    int deleteByPrimaryKey(@Param("idEntidadfed") Short idEntidadfed, @Param("idMunicipio") Integer idMunicipio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consejo_mun1415
     *
     * @mbggenerated Wed Feb 11 12:01:48 CST 2015
     */
    int insert(ConsejoMun1415 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consejo_mun1415
     *
     * @mbggenerated Wed Feb 11 12:01:48 CST 2015
     */
    int insertSelective(ConsejoMun1415 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consejo_mun1415
     *
     * @mbggenerated Wed Feb 11 12:01:48 CST 2015
     */
    List<ConsejoMun1415> selectByExample(ConsejoMun1415Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consejo_mun1415
     *
     * @mbggenerated Wed Feb 11 12:01:48 CST 2015
     */
    ConsejoMun1415 selectByPrimaryKey(@Param("idEntidadfed") Short idEntidadfed, @Param("idMunicipio") Integer idMunicipio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consejo_mun1415
     *
     * @mbggenerated Wed Feb 11 12:01:48 CST 2015
     */
    int updateByExampleSelective(@Param("record") ConsejoMun1415 record, @Param("example") ConsejoMun1415Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consejo_mun1415
     *
     * @mbggenerated Wed Feb 11 12:01:48 CST 2015
     */
    int updateByExample(@Param("record") ConsejoMun1415 record, @Param("example") ConsejoMun1415Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consejo_mun1415
     *
     * @mbggenerated Wed Feb 11 12:01:48 CST 2015
     */
    int updateByPrimaryKeySelective(ConsejoMun1415 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consejo_mun1415
     *
     * @mbggenerated Wed Feb 11 12:01:48 CST 2015
     */
    int updateByPrimaryKey(ConsejoMun1415 record);
}