package mx.gob.sep.dgtec.repuce.dao;

import java.util.List;
import mx.gob.sep.dgtec.repuce.model.CTipoAccion;
import mx.gob.sep.dgtec.repuce.model.CTipoAccionExample;
import org.apache.ibatis.annotations.Param;

public interface CTipoAccionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_accion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int countByExample(CTipoAccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_accion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int deleteByExample(CTipoAccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_accion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int deleteByPrimaryKey(Short cTipoAccion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_accion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int insert(CTipoAccion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_accion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int insertSelective(CTipoAccion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_accion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    List<CTipoAccion> selectByExample(CTipoAccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_accion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    CTipoAccion selectByPrimaryKey(Short cTipoAccion);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_accion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByExampleSelective(@Param("record") CTipoAccion record, @Param("example") CTipoAccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_accion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByExample(@Param("record") CTipoAccion record, @Param("example") CTipoAccionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_accion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByPrimaryKeySelective(CTipoAccion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_accion
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    int updateByPrimaryKey(CTipoAccion record);
}