package mx.gob.sep.dgtec.repuce.model;

public class ApecNecesidadesEducativas {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.c_apec
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private Integer cApec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.c_reunion
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private Short cReunion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.c_apoyo
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private Integer cApoyo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.c_nee
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private Integer cNee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.cuantos
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private Integer cuantos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.gestionar
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private String gestionar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.c_nee1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private Integer cNee1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.cuantos1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private Integer cuantos1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.gestionar1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private String gestionar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.concreto
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private String concreto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.proceso
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private String proceso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.concreto1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private String concreto1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.proceso1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private String proceso1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.beneficiarios
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private Integer beneficiarios;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.beneficiarios1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private Integer beneficiarios1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.seconcreto
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private String seconcreto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.consiste
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private String consiste;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.seconcreto1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private String seconcreto1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_necesidades_educativas.consiste1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    private String consiste1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.c_apec
     *
     * @return the value of apec_necesidades_educativas.c_apec
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public Integer getcApec() {
        return cApec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.c_apec
     *
     * @param cApec the value for apec_necesidades_educativas.c_apec
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setcApec(Integer cApec) {
        this.cApec = cApec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.c_reunion
     *
     * @return the value of apec_necesidades_educativas.c_reunion
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public Short getcReunion() {
        return cReunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.c_reunion
     *
     * @param cReunion the value for apec_necesidades_educativas.c_reunion
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setcReunion(Short cReunion) {
        this.cReunion = cReunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.c_apoyo
     *
     * @return the value of apec_necesidades_educativas.c_apoyo
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public Integer getcApoyo() {
        return cApoyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.c_apoyo
     *
     * @param cApoyo the value for apec_necesidades_educativas.c_apoyo
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setcApoyo(Integer cApoyo) {
        this.cApoyo = cApoyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.c_nee
     *
     * @return the value of apec_necesidades_educativas.c_nee
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public Integer getcNee() {
        return cNee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.c_nee
     *
     * @param cNee the value for apec_necesidades_educativas.c_nee
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setcNee(Integer cNee) {
        this.cNee = cNee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.cuantos
     *
     * @return the value of apec_necesidades_educativas.cuantos
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public Integer getCuantos() {
        return cuantos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.cuantos
     *
     * @param cuantos the value for apec_necesidades_educativas.cuantos
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setCuantos(Integer cuantos) {
        this.cuantos = cuantos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.gestionar
     *
     * @return the value of apec_necesidades_educativas.gestionar
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public String getGestionar() {
        return gestionar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.gestionar
     *
     * @param gestionar the value for apec_necesidades_educativas.gestionar
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setGestionar(String gestionar) {
        this.gestionar = gestionar == null ? null : gestionar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.c_nee1
     *
     * @return the value of apec_necesidades_educativas.c_nee1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public Integer getcNee1() {
        return cNee1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.c_nee1
     *
     * @param cNee1 the value for apec_necesidades_educativas.c_nee1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setcNee1(Integer cNee1) {
        this.cNee1 = cNee1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.cuantos1
     *
     * @return the value of apec_necesidades_educativas.cuantos1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public Integer getCuantos1() {
        return cuantos1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.cuantos1
     *
     * @param cuantos1 the value for apec_necesidades_educativas.cuantos1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setCuantos1(Integer cuantos1) {
        this.cuantos1 = cuantos1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.gestionar1
     *
     * @return the value of apec_necesidades_educativas.gestionar1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public String getGestionar1() {
        return gestionar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.gestionar1
     *
     * @param gestionar1 the value for apec_necesidades_educativas.gestionar1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setGestionar1(String gestionar1) {
        this.gestionar1 = gestionar1 == null ? null : gestionar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.concreto
     *
     * @return the value of apec_necesidades_educativas.concreto
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public String getConcreto() {
        return concreto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.concreto
     *
     * @param concreto the value for apec_necesidades_educativas.concreto
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setConcreto(String concreto) {
        this.concreto = concreto == null ? null : concreto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.proceso
     *
     * @return the value of apec_necesidades_educativas.proceso
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public String getProceso() {
        return proceso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.proceso
     *
     * @param proceso the value for apec_necesidades_educativas.proceso
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setProceso(String proceso) {
        this.proceso = proceso == null ? null : proceso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.concreto1
     *
     * @return the value of apec_necesidades_educativas.concreto1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public String getConcreto1() {
        return concreto1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.concreto1
     *
     * @param concreto1 the value for apec_necesidades_educativas.concreto1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setConcreto1(String concreto1) {
        this.concreto1 = concreto1 == null ? null : concreto1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.proceso1
     *
     * @return the value of apec_necesidades_educativas.proceso1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public String getProceso1() {
        return proceso1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.proceso1
     *
     * @param proceso1 the value for apec_necesidades_educativas.proceso1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setProceso1(String proceso1) {
        this.proceso1 = proceso1 == null ? null : proceso1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.beneficiarios
     *
     * @return the value of apec_necesidades_educativas.beneficiarios
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public Integer getBeneficiarios() {
        return beneficiarios;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.beneficiarios
     *
     * @param beneficiarios the value for apec_necesidades_educativas.beneficiarios
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setBeneficiarios(Integer beneficiarios) {
        this.beneficiarios = beneficiarios;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.beneficiarios1
     *
     * @return the value of apec_necesidades_educativas.beneficiarios1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public Integer getBeneficiarios1() {
        return beneficiarios1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.beneficiarios1
     *
     * @param beneficiarios1 the value for apec_necesidades_educativas.beneficiarios1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setBeneficiarios1(Integer beneficiarios1) {
        this.beneficiarios1 = beneficiarios1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.seconcreto
     *
     * @return the value of apec_necesidades_educativas.seconcreto
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public String getSeconcreto() {
        return seconcreto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.seconcreto
     *
     * @param seconcreto the value for apec_necesidades_educativas.seconcreto
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setSeconcreto(String seconcreto) {
        this.seconcreto = seconcreto == null ? null : seconcreto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.consiste
     *
     * @return the value of apec_necesidades_educativas.consiste
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public String getConsiste() {
        return consiste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.consiste
     *
     * @param consiste the value for apec_necesidades_educativas.consiste
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setConsiste(String consiste) {
        this.consiste = consiste == null ? null : consiste.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.seconcreto1
     *
     * @return the value of apec_necesidades_educativas.seconcreto1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public String getSeconcreto1() {
        return seconcreto1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.seconcreto1
     *
     * @param seconcreto1 the value for apec_necesidades_educativas.seconcreto1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setSeconcreto1(String seconcreto1) {
        this.seconcreto1 = seconcreto1 == null ? null : seconcreto1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_necesidades_educativas.consiste1
     *
     * @return the value of apec_necesidades_educativas.consiste1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public String getConsiste1() {
        return consiste1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_necesidades_educativas.consiste1
     *
     * @param consiste1 the value for apec_necesidades_educativas.consiste1
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    public void setConsiste1(String consiste1) {
        this.consiste1 = consiste1 == null ? null : consiste1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_necesidades_educativas
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ApecNecesidadesEducativas other = (ApecNecesidadesEducativas) that;
        return (this.getcApec() == null ? other.getcApec() == null : this.getcApec().equals(other.getcApec()))
            && (this.getcReunion() == null ? other.getcReunion() == null : this.getcReunion().equals(other.getcReunion()))
            && (this.getcApoyo() == null ? other.getcApoyo() == null : this.getcApoyo().equals(other.getcApoyo()))
            && (this.getcNee() == null ? other.getcNee() == null : this.getcNee().equals(other.getcNee()))
            && (this.getCuantos() == null ? other.getCuantos() == null : this.getCuantos().equals(other.getCuantos()))
            && (this.getGestionar() == null ? other.getGestionar() == null : this.getGestionar().equals(other.getGestionar()))
            && (this.getcNee1() == null ? other.getcNee1() == null : this.getcNee1().equals(other.getcNee1()))
            && (this.getCuantos1() == null ? other.getCuantos1() == null : this.getCuantos1().equals(other.getCuantos1()))
            && (this.getGestionar1() == null ? other.getGestionar1() == null : this.getGestionar1().equals(other.getGestionar1()))
            && (this.getConcreto() == null ? other.getConcreto() == null : this.getConcreto().equals(other.getConcreto()))
            && (this.getProceso() == null ? other.getProceso() == null : this.getProceso().equals(other.getProceso()))
            && (this.getConcreto1() == null ? other.getConcreto1() == null : this.getConcreto1().equals(other.getConcreto1()))
            && (this.getProceso1() == null ? other.getProceso1() == null : this.getProceso1().equals(other.getProceso1()))
            && (this.getBeneficiarios() == null ? other.getBeneficiarios() == null : this.getBeneficiarios().equals(other.getBeneficiarios()))
            && (this.getBeneficiarios1() == null ? other.getBeneficiarios1() == null : this.getBeneficiarios1().equals(other.getBeneficiarios1()))
            && (this.getSeconcreto() == null ? other.getSeconcreto() == null : this.getSeconcreto().equals(other.getSeconcreto()))
            && (this.getConsiste() == null ? other.getConsiste() == null : this.getConsiste().equals(other.getConsiste()))
            && (this.getSeconcreto1() == null ? other.getSeconcreto1() == null : this.getSeconcreto1().equals(other.getSeconcreto1()))
            && (this.getConsiste1() == null ? other.getConsiste1() == null : this.getConsiste1().equals(other.getConsiste1()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_necesidades_educativas
     *
     * @mbggenerated Fri Jul 07 13:34:32 CDT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcApec() == null) ? 0 : getcApec().hashCode());
        result = prime * result + ((getcReunion() == null) ? 0 : getcReunion().hashCode());
        result = prime * result + ((getcApoyo() == null) ? 0 : getcApoyo().hashCode());
        result = prime * result + ((getcNee() == null) ? 0 : getcNee().hashCode());
        result = prime * result + ((getCuantos() == null) ? 0 : getCuantos().hashCode());
        result = prime * result + ((getGestionar() == null) ? 0 : getGestionar().hashCode());
        result = prime * result + ((getcNee1() == null) ? 0 : getcNee1().hashCode());
        result = prime * result + ((getCuantos1() == null) ? 0 : getCuantos1().hashCode());
        result = prime * result + ((getGestionar1() == null) ? 0 : getGestionar1().hashCode());
        result = prime * result + ((getConcreto() == null) ? 0 : getConcreto().hashCode());
        result = prime * result + ((getProceso() == null) ? 0 : getProceso().hashCode());
        result = prime * result + ((getConcreto1() == null) ? 0 : getConcreto1().hashCode());
        result = prime * result + ((getProceso1() == null) ? 0 : getProceso1().hashCode());
        result = prime * result + ((getBeneficiarios() == null) ? 0 : getBeneficiarios().hashCode());
        result = prime * result + ((getBeneficiarios1() == null) ? 0 : getBeneficiarios1().hashCode());
        result = prime * result + ((getSeconcreto() == null) ? 0 : getSeconcreto().hashCode());
        result = prime * result + ((getConsiste() == null) ? 0 : getConsiste().hashCode());
        result = prime * result + ((getSeconcreto1() == null) ? 0 : getSeconcreto1().hashCode());
        result = prime * result + ((getConsiste1() == null) ? 0 : getConsiste1().hashCode());
        return result;
    }
}