package mx.gob.sep.dgtec.repuce.model;

public class ApecAsistente {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_asistente.c_apec
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    private Integer cApec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_asistente.c_reunion
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    private Short cReunion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_asistente.c_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    private Short cAsistente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_asistente.paterno_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    private String paternoAsistente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_asistente.materno_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    private String maternoAsistente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_asistente.nombre_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    private String nombreAsistente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_asistente.genero
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    private String genero;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_asistente.edad
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    private Short edad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apec_asistente.c_niveleduc
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    private Integer cNiveleduc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_asistente.c_apec
     *
     * @return the value of apec_asistente.c_apec
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public Integer getcApec() {
        return cApec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_asistente.c_apec
     *
     * @param cApec the value for apec_asistente.c_apec
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public void setcApec(Integer cApec) {
        this.cApec = cApec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_asistente.c_reunion
     *
     * @return the value of apec_asistente.c_reunion
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public Short getcReunion() {
        return cReunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_asistente.c_reunion
     *
     * @param cReunion the value for apec_asistente.c_reunion
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public void setcReunion(Short cReunion) {
        this.cReunion = cReunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_asistente.c_asistente
     *
     * @return the value of apec_asistente.c_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public Short getcAsistente() {
        return cAsistente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_asistente.c_asistente
     *
     * @param cAsistente the value for apec_asistente.c_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public void setcAsistente(Short cAsistente) {
        this.cAsistente = cAsistente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_asistente.paterno_asistente
     *
     * @return the value of apec_asistente.paterno_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public String getPaternoAsistente() {
        return paternoAsistente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_asistente.paterno_asistente
     *
     * @param paternoAsistente the value for apec_asistente.paterno_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public void setPaternoAsistente(String paternoAsistente) {
        this.paternoAsistente = paternoAsistente == null ? null : paternoAsistente.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_asistente.materno_asistente
     *
     * @return the value of apec_asistente.materno_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public String getMaternoAsistente() {
        return maternoAsistente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_asistente.materno_asistente
     *
     * @param maternoAsistente the value for apec_asistente.materno_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public void setMaternoAsistente(String maternoAsistente) {
        this.maternoAsistente = maternoAsistente == null ? null : maternoAsistente.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_asistente.nombre_asistente
     *
     * @return the value of apec_asistente.nombre_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public String getNombreAsistente() {
        return nombreAsistente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_asistente.nombre_asistente
     *
     * @param nombreAsistente the value for apec_asistente.nombre_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public void setNombreAsistente(String nombreAsistente) {
        this.nombreAsistente = nombreAsistente == null ? null : nombreAsistente.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_asistente.genero
     *
     * @return the value of apec_asistente.genero
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public String getGenero() {
        return genero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_asistente.genero
     *
     * @param genero the value for apec_asistente.genero
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public void setGenero(String genero) {
        this.genero = genero == null ? null : genero.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_asistente.edad
     *
     * @return the value of apec_asistente.edad
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public Short getEdad() {
        return edad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_asistente.edad
     *
     * @param edad the value for apec_asistente.edad
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public void setEdad(Short edad) {
        this.edad = edad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apec_asistente.c_niveleduc
     *
     * @return the value of apec_asistente.c_niveleduc
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public Integer getcNiveleduc() {
        return cNiveleduc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apec_asistente.c_niveleduc
     *
     * @param cNiveleduc the value for apec_asistente.c_niveleduc
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    public void setcNiveleduc(Integer cNiveleduc) {
        this.cNiveleduc = cNiveleduc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ApecAsistente other = (ApecAsistente) that;
        return (this.getcApec() == null ? other.getcApec() == null : this.getcApec().equals(other.getcApec()))
            && (this.getcReunion() == null ? other.getcReunion() == null : this.getcReunion().equals(other.getcReunion()))
            && (this.getcAsistente() == null ? other.getcAsistente() == null : this.getcAsistente().equals(other.getcAsistente()))
            && (this.getPaternoAsistente() == null ? other.getPaternoAsistente() == null : this.getPaternoAsistente().equals(other.getPaternoAsistente()))
            && (this.getMaternoAsistente() == null ? other.getMaternoAsistente() == null : this.getMaternoAsistente().equals(other.getMaternoAsistente()))
            && (this.getNombreAsistente() == null ? other.getNombreAsistente() == null : this.getNombreAsistente().equals(other.getNombreAsistente()))
            && (this.getGenero() == null ? other.getGenero() == null : this.getGenero().equals(other.getGenero()))
            && (this.getEdad() == null ? other.getEdad() == null : this.getEdad().equals(other.getEdad()))
            && (this.getcNiveleduc() == null ? other.getcNiveleduc() == null : this.getcNiveleduc().equals(other.getcNiveleduc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apec_asistente
     *
     * @mbggenerated Thu Sep 19 10:19:54 CDT 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcApec() == null) ? 0 : getcApec().hashCode());
        result = prime * result + ((getcReunion() == null) ? 0 : getcReunion().hashCode());
        result = prime * result + ((getcAsistente() == null) ? 0 : getcAsistente().hashCode());
        result = prime * result + ((getPaternoAsistente() == null) ? 0 : getPaternoAsistente().hashCode());
        result = prime * result + ((getMaternoAsistente() == null) ? 0 : getMaternoAsistente().hashCode());
        result = prime * result + ((getNombreAsistente() == null) ? 0 : getNombreAsistente().hashCode());
        result = prime * result + ((getGenero() == null) ? 0 : getGenero().hashCode());
        result = prime * result + ((getEdad() == null) ? 0 : getEdad().hashCode());
        result = prime * result + ((getcNiveleduc() == null) ? 0 : getcNiveleduc().hashCode());
        return result;
    }
}