package mx.gob.sep.dgtec.repuce.model;

public class CApoyo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.c_apoyo
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private Integer cApoyo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.c_tipo_apoyo
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private Short cTipoApoyo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.descrip_larga
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private String descripLarga;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.descrip_corta
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private String descripCorta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.economico
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private Boolean economico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.especie
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private Boolean especie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.beneficiarios
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private Boolean beneficiarios;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.otra_descripcion
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private Boolean otraDescripcion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.otro_tipo_beneficiarios
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private String otroTipoBeneficiarios;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.siempre_visible
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private Boolean siempreVisible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.visible_en_reunion
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private Short visibleEnReunion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_apoyo.beneficiariosr3
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    private Boolean beneficiariosr3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.c_apoyo
     *
     * @return the value of c_apoyo.c_apoyo
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public Integer getcApoyo() {
        return cApoyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.c_apoyo
     *
     * @param cApoyo the value for c_apoyo.c_apoyo
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setcApoyo(Integer cApoyo) {
        this.cApoyo = cApoyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.c_tipo_apoyo
     *
     * @return the value of c_apoyo.c_tipo_apoyo
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public Short getcTipoApoyo() {
        return cTipoApoyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.c_tipo_apoyo
     *
     * @param cTipoApoyo the value for c_apoyo.c_tipo_apoyo
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setcTipoApoyo(Short cTipoApoyo) {
        this.cTipoApoyo = cTipoApoyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.descrip_larga
     *
     * @return the value of c_apoyo.descrip_larga
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public String getDescripLarga() {
        return descripLarga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.descrip_larga
     *
     * @param descripLarga the value for c_apoyo.descrip_larga
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setDescripLarga(String descripLarga) {
        this.descripLarga = descripLarga == null ? null : descripLarga.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.descrip_corta
     *
     * @return the value of c_apoyo.descrip_corta
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public String getDescripCorta() {
        return descripCorta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.descrip_corta
     *
     * @param descripCorta the value for c_apoyo.descrip_corta
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setDescripCorta(String descripCorta) {
        this.descripCorta = descripCorta == null ? null : descripCorta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.economico
     *
     * @return the value of c_apoyo.economico
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public Boolean getEconomico() {
        return economico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.economico
     *
     * @param economico the value for c_apoyo.economico
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setEconomico(Boolean economico) {
        this.economico = economico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.especie
     *
     * @return the value of c_apoyo.especie
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public Boolean getEspecie() {
        return especie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.especie
     *
     * @param especie the value for c_apoyo.especie
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setEspecie(Boolean especie) {
        this.especie = especie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.beneficiarios
     *
     * @return the value of c_apoyo.beneficiarios
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public Boolean getBeneficiarios() {
        return beneficiarios;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.beneficiarios
     *
     * @param beneficiarios the value for c_apoyo.beneficiarios
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setBeneficiarios(Boolean beneficiarios) {
        this.beneficiarios = beneficiarios;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.otra_descripcion
     *
     * @return the value of c_apoyo.otra_descripcion
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public Boolean getOtraDescripcion() {
        return otraDescripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.otra_descripcion
     *
     * @param otraDescripcion the value for c_apoyo.otra_descripcion
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setOtraDescripcion(Boolean otraDescripcion) {
        this.otraDescripcion = otraDescripcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.otro_tipo_beneficiarios
     *
     * @return the value of c_apoyo.otro_tipo_beneficiarios
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public String getOtroTipoBeneficiarios() {
        return otroTipoBeneficiarios;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.otro_tipo_beneficiarios
     *
     * @param otroTipoBeneficiarios the value for c_apoyo.otro_tipo_beneficiarios
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setOtroTipoBeneficiarios(String otroTipoBeneficiarios) {
        this.otroTipoBeneficiarios = otroTipoBeneficiarios == null ? null : otroTipoBeneficiarios.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.siempre_visible
     *
     * @return the value of c_apoyo.siempre_visible
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public Boolean getSiempreVisible() {
        return siempreVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.siempre_visible
     *
     * @param siempreVisible the value for c_apoyo.siempre_visible
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setSiempreVisible(Boolean siempreVisible) {
        this.siempreVisible = siempreVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.visible_en_reunion
     *
     * @return the value of c_apoyo.visible_en_reunion
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public Short getVisibleEnReunion() {
        return visibleEnReunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.visible_en_reunion
     *
     * @param visibleEnReunion the value for c_apoyo.visible_en_reunion
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setVisibleEnReunion(Short visibleEnReunion) {
        this.visibleEnReunion = visibleEnReunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_apoyo.beneficiariosr3
     *
     * @return the value of c_apoyo.beneficiariosr3
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public Boolean getBeneficiariosr3() {
        return beneficiariosr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_apoyo.beneficiariosr3
     *
     * @param beneficiariosr3 the value for c_apoyo.beneficiariosr3
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    public void setBeneficiariosr3(Boolean beneficiariosr3) {
        this.beneficiariosr3 = beneficiariosr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_apoyo
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CApoyo other = (CApoyo) that;
        return (this.getcApoyo() == null ? other.getcApoyo() == null : this.getcApoyo().equals(other.getcApoyo()))
            && (this.getcTipoApoyo() == null ? other.getcTipoApoyo() == null : this.getcTipoApoyo().equals(other.getcTipoApoyo()))
            && (this.getDescripLarga() == null ? other.getDescripLarga() == null : this.getDescripLarga().equals(other.getDescripLarga()))
            && (this.getDescripCorta() == null ? other.getDescripCorta() == null : this.getDescripCorta().equals(other.getDescripCorta()))
            && (this.getEconomico() == null ? other.getEconomico() == null : this.getEconomico().equals(other.getEconomico()))
            && (this.getEspecie() == null ? other.getEspecie() == null : this.getEspecie().equals(other.getEspecie()))
            && (this.getBeneficiarios() == null ? other.getBeneficiarios() == null : this.getBeneficiarios().equals(other.getBeneficiarios()))
            && (this.getOtraDescripcion() == null ? other.getOtraDescripcion() == null : this.getOtraDescripcion().equals(other.getOtraDescripcion()))
            && (this.getOtroTipoBeneficiarios() == null ? other.getOtroTipoBeneficiarios() == null : this.getOtroTipoBeneficiarios().equals(other.getOtroTipoBeneficiarios()))
            && (this.getSiempreVisible() == null ? other.getSiempreVisible() == null : this.getSiempreVisible().equals(other.getSiempreVisible()))
            && (this.getVisibleEnReunion() == null ? other.getVisibleEnReunion() == null : this.getVisibleEnReunion().equals(other.getVisibleEnReunion()))
            && (this.getBeneficiariosr3() == null ? other.getBeneficiariosr3() == null : this.getBeneficiariosr3().equals(other.getBeneficiariosr3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_apoyo
     *
     * @mbggenerated Thu Dec 05 10:20:02 CST 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcApoyo() == null) ? 0 : getcApoyo().hashCode());
        result = prime * result + ((getcTipoApoyo() == null) ? 0 : getcTipoApoyo().hashCode());
        result = prime * result + ((getDescripLarga() == null) ? 0 : getDescripLarga().hashCode());
        result = prime * result + ((getDescripCorta() == null) ? 0 : getDescripCorta().hashCode());
        result = prime * result + ((getEconomico() == null) ? 0 : getEconomico().hashCode());
        result = prime * result + ((getEspecie() == null) ? 0 : getEspecie().hashCode());
        result = prime * result + ((getBeneficiarios() == null) ? 0 : getBeneficiarios().hashCode());
        result = prime * result + ((getOtraDescripcion() == null) ? 0 : getOtraDescripcion().hashCode());
        result = prime * result + ((getOtroTipoBeneficiarios() == null) ? 0 : getOtroTipoBeneficiarios().hashCode());
        result = prime * result + ((getSiempreVisible() == null) ? 0 : getSiempreVisible().hashCode());
        result = prime * result + ((getVisibleEnReunion() == null) ? 0 : getVisibleEnReunion().hashCode());
        result = prime * result + ((getBeneficiariosr3() == null) ? 0 : getBeneficiariosr3().hashCode());
        return result;
    }
}