package mx.gob.sep.dgtec.repuce.model;

import java.util.Date;

public class CCalidadInt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_calidad_int.c_calidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Integer cCalidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_calidad_int.nom_calidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String nomCalidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_calidad_int.fch_sistema_ini
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Date fchSistemaIni;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_calidad_int.fch_sistema_fin
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Date fchSistemaFin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_calidad_int.d_vigencia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String dVigencia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_calidad_int.c_calidad
     *
     * @return the value of c_calidad_int.c_calidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Integer getcCalidad() {
        return cCalidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_calidad_int.c_calidad
     *
     * @param cCalidad the value for c_calidad_int.c_calidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setcCalidad(Integer cCalidad) {
        this.cCalidad = cCalidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_calidad_int.nom_calidad
     *
     * @return the value of c_calidad_int.nom_calidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getNomCalidad() {
        return nomCalidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_calidad_int.nom_calidad
     *
     * @param nomCalidad the value for c_calidad_int.nom_calidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setNomCalidad(String nomCalidad) {
        this.nomCalidad = nomCalidad == null ? null : nomCalidad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_calidad_int.fch_sistema_ini
     *
     * @return the value of c_calidad_int.fch_sistema_ini
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Date getFchSistemaIni() {
        return fchSistemaIni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_calidad_int.fch_sistema_ini
     *
     * @param fchSistemaIni the value for c_calidad_int.fch_sistema_ini
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setFchSistemaIni(Date fchSistemaIni) {
        this.fchSistemaIni = fchSistemaIni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_calidad_int.fch_sistema_fin
     *
     * @return the value of c_calidad_int.fch_sistema_fin
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Date getFchSistemaFin() {
        return fchSistemaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_calidad_int.fch_sistema_fin
     *
     * @param fchSistemaFin the value for c_calidad_int.fch_sistema_fin
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setFchSistemaFin(Date fchSistemaFin) {
        this.fchSistemaFin = fchSistemaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_calidad_int.d_vigencia
     *
     * @return the value of c_calidad_int.d_vigencia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getdVigencia() {
        return dVigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_calidad_int.d_vigencia
     *
     * @param dVigencia the value for c_calidad_int.d_vigencia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setdVigencia(String dVigencia) {
        this.dVigencia = dVigencia == null ? null : dVigencia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CCalidadInt other = (CCalidadInt) that;
        return (this.getcCalidad() == null ? other.getcCalidad() == null : this.getcCalidad().equals(other.getcCalidad()))
            && (this.getNomCalidad() == null ? other.getNomCalidad() == null : this.getNomCalidad().equals(other.getNomCalidad()))
            && (this.getFchSistemaIni() == null ? other.getFchSistemaIni() == null : this.getFchSistemaIni().equals(other.getFchSistemaIni()))
            && (this.getFchSistemaFin() == null ? other.getFchSistemaFin() == null : this.getFchSistemaFin().equals(other.getFchSistemaFin()))
            && (this.getdVigencia() == null ? other.getdVigencia() == null : this.getdVigencia().equals(other.getdVigencia()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_calidad_int
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcCalidad() == null) ? 0 : getcCalidad().hashCode());
        result = prime * result + ((getNomCalidad() == null) ? 0 : getNomCalidad().hashCode());
        result = prime * result + ((getFchSistemaIni() == null) ? 0 : getFchSistemaIni().hashCode());
        result = prime * result + ((getFchSistemaFin() == null) ? 0 : getFchSistemaFin().hashCode());
        result = prime * result + ((getdVigencia() == null) ? 0 : getdVigencia().hashCode());
        return result;
    }
}