package mx.gob.sep.dgtec.repuce.model;

import java.util.Date;

public class CCoNee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_co_nee.c_nee
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    private Integer cNee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_co_nee.nom_nee
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    private String nomNee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_co_nee.nomc_nee
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    private String nomcNee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_co_nee.fch_sistema_ini
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    private Date fchSistemaIni;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_co_nee.fch_sistema_fin
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    private Date fchSistemaFin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_co_nee.d_vigencia
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    private String dVigencia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_co_nee.c_nee
     *
     * @return the value of c_co_nee.c_nee
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public Integer getcNee() {
        return cNee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_co_nee.c_nee
     *
     * @param cNee the value for c_co_nee.c_nee
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public void setcNee(Integer cNee) {
        this.cNee = cNee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_co_nee.nom_nee
     *
     * @return the value of c_co_nee.nom_nee
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public String getNomNee() {
        return nomNee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_co_nee.nom_nee
     *
     * @param nomNee the value for c_co_nee.nom_nee
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public void setNomNee(String nomNee) {
        this.nomNee = nomNee == null ? null : nomNee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_co_nee.nomc_nee
     *
     * @return the value of c_co_nee.nomc_nee
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public String getNomcNee() {
        return nomcNee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_co_nee.nomc_nee
     *
     * @param nomcNee the value for c_co_nee.nomc_nee
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public void setNomcNee(String nomcNee) {
        this.nomcNee = nomcNee == null ? null : nomcNee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_co_nee.fch_sistema_ini
     *
     * @return the value of c_co_nee.fch_sistema_ini
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public Date getFchSistemaIni() {
        return fchSistemaIni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_co_nee.fch_sistema_ini
     *
     * @param fchSistemaIni the value for c_co_nee.fch_sistema_ini
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public void setFchSistemaIni(Date fchSistemaIni) {
        this.fchSistemaIni = fchSistemaIni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_co_nee.fch_sistema_fin
     *
     * @return the value of c_co_nee.fch_sistema_fin
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public Date getFchSistemaFin() {
        return fchSistemaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_co_nee.fch_sistema_fin
     *
     * @param fchSistemaFin the value for c_co_nee.fch_sistema_fin
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public void setFchSistemaFin(Date fchSistemaFin) {
        this.fchSistemaFin = fchSistemaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_co_nee.d_vigencia
     *
     * @return the value of c_co_nee.d_vigencia
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public String getdVigencia() {
        return dVigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_co_nee.d_vigencia
     *
     * @param dVigencia the value for c_co_nee.d_vigencia
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    public void setdVigencia(String dVigencia) {
        this.dVigencia = dVigencia == null ? null : dVigencia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_co_nee
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CCoNee other = (CCoNee) that;
        return (this.getcNee() == null ? other.getcNee() == null : this.getcNee().equals(other.getcNee()))
            && (this.getNomNee() == null ? other.getNomNee() == null : this.getNomNee().equals(other.getNomNee()))
            && (this.getNomcNee() == null ? other.getNomcNee() == null : this.getNomcNee().equals(other.getNomcNee()))
            && (this.getFchSistemaIni() == null ? other.getFchSistemaIni() == null : this.getFchSistemaIni().equals(other.getFchSistemaIni()))
            && (this.getFchSistemaFin() == null ? other.getFchSistemaFin() == null : this.getFchSistemaFin().equals(other.getFchSistemaFin()))
            && (this.getdVigencia() == null ? other.getdVigencia() == null : this.getdVigencia().equals(other.getdVigencia()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_co_nee
     *
     * @mbggenerated Wed Apr 15 17:44:37 CDT 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcNee() == null) ? 0 : getcNee().hashCode());
        result = prime * result + ((getNomNee() == null) ? 0 : getNomNee().hashCode());
        result = prime * result + ((getNomcNee() == null) ? 0 : getNomcNee().hashCode());
        result = prime * result + ((getFchSistemaIni() == null) ? 0 : getFchSistemaIni().hashCode());
        result = prime * result + ((getFchSistemaFin() == null) ? 0 : getFchSistemaFin().hashCode());
        result = prime * result + ((getdVigencia() == null) ? 0 : getdVigencia().hashCode());
        return result;
    }
}