package mx.gob.sep.dgtec.repuce.model;

import java.util.ArrayList;
import java.util.List;

public class CeCompromisosExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    public CeCompromisosExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCCctIsNull() {
            addCriterion("c_cct is null");
            return (Criteria) this;
        }

        public Criteria andCCctIsNotNull() {
            addCriterion("c_cct is not null");
            return (Criteria) this;
        }

        public Criteria andCCctEqualTo(Integer value) {
            addCriterion("c_cct =", value, "cCct");
            return (Criteria) this;
        }

        public Criteria andCCctNotEqualTo(Integer value) {
            addCriterion("c_cct <>", value, "cCct");
            return (Criteria) this;
        }

        public Criteria andCCctGreaterThan(Integer value) {
            addCriterion("c_cct >", value, "cCct");
            return (Criteria) this;
        }

        public Criteria andCCctGreaterThanOrEqualTo(Integer value) {
            addCriterion("c_cct >=", value, "cCct");
            return (Criteria) this;
        }

        public Criteria andCCctLessThan(Integer value) {
            addCriterion("c_cct <", value, "cCct");
            return (Criteria) this;
        }

        public Criteria andCCctLessThanOrEqualTo(Integer value) {
            addCriterion("c_cct <=", value, "cCct");
            return (Criteria) this;
        }

        public Criteria andCCctIn(List<Integer> values) {
            addCriterion("c_cct in", values, "cCct");
            return (Criteria) this;
        }

        public Criteria andCCctNotIn(List<Integer> values) {
            addCriterion("c_cct not in", values, "cCct");
            return (Criteria) this;
        }

        public Criteria andCCctBetween(Integer value1, Integer value2) {
            addCriterion("c_cct between", value1, value2, "cCct");
            return (Criteria) this;
        }

        public Criteria andCCctNotBetween(Integer value1, Integer value2) {
            addCriterion("c_cct not between", value1, value2, "cCct");
            return (Criteria) this;
        }

        public Criteria andCSesionIsNull() {
            addCriterion("c_sesion is null");
            return (Criteria) this;
        }

        public Criteria andCSesionIsNotNull() {
            addCriterion("c_sesion is not null");
            return (Criteria) this;
        }

        public Criteria andCSesionEqualTo(Short value) {
            addCriterion("c_sesion =", value, "cSesion");
            return (Criteria) this;
        }

        public Criteria andCSesionNotEqualTo(Short value) {
            addCriterion("c_sesion <>", value, "cSesion");
            return (Criteria) this;
        }

        public Criteria andCSesionGreaterThan(Short value) {
            addCriterion("c_sesion >", value, "cSesion");
            return (Criteria) this;
        }

        public Criteria andCSesionGreaterThanOrEqualTo(Short value) {
            addCriterion("c_sesion >=", value, "cSesion");
            return (Criteria) this;
        }

        public Criteria andCSesionLessThan(Short value) {
            addCriterion("c_sesion <", value, "cSesion");
            return (Criteria) this;
        }

        public Criteria andCSesionLessThanOrEqualTo(Short value) {
            addCriterion("c_sesion <=", value, "cSesion");
            return (Criteria) this;
        }

        public Criteria andCSesionIn(List<Short> values) {
            addCriterion("c_sesion in", values, "cSesion");
            return (Criteria) this;
        }

        public Criteria andCSesionNotIn(List<Short> values) {
            addCriterion("c_sesion not in", values, "cSesion");
            return (Criteria) this;
        }

        public Criteria andCSesionBetween(Short value1, Short value2) {
            addCriterion("c_sesion between", value1, value2, "cSesion");
            return (Criteria) this;
        }

        public Criteria andCSesionNotBetween(Short value1, Short value2) {
            addCriterion("c_sesion not between", value1, value2, "cSesion");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoIsNull() {
            addCriterion("id_compromiso is null");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoIsNotNull() {
            addCriterion("id_compromiso is not null");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoEqualTo(Short value) {
            addCriterion("id_compromiso =", value, "idCompromiso");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoNotEqualTo(Short value) {
            addCriterion("id_compromiso <>", value, "idCompromiso");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoGreaterThan(Short value) {
            addCriterion("id_compromiso >", value, "idCompromiso");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoGreaterThanOrEqualTo(Short value) {
            addCriterion("id_compromiso >=", value, "idCompromiso");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoLessThan(Short value) {
            addCriterion("id_compromiso <", value, "idCompromiso");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoLessThanOrEqualTo(Short value) {
            addCriterion("id_compromiso <=", value, "idCompromiso");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoIn(List<Short> values) {
            addCriterion("id_compromiso in", values, "idCompromiso");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoNotIn(List<Short> values) {
            addCriterion("id_compromiso not in", values, "idCompromiso");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoBetween(Short value1, Short value2) {
            addCriterion("id_compromiso between", value1, value2, "idCompromiso");
            return (Criteria) this;
        }

        public Criteria andIdCompromisoNotBetween(Short value1, Short value2) {
            addCriterion("id_compromiso not between", value1, value2, "idCompromiso");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoIsNull() {
            addCriterion("id_consecutivo is null");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoIsNotNull() {
            addCriterion("id_consecutivo is not null");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoEqualTo(Short value) {
            addCriterion("id_consecutivo =", value, "idConsecutivo");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoNotEqualTo(Short value) {
            addCriterion("id_consecutivo <>", value, "idConsecutivo");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoGreaterThan(Short value) {
            addCriterion("id_consecutivo >", value, "idConsecutivo");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoGreaterThanOrEqualTo(Short value) {
            addCriterion("id_consecutivo >=", value, "idConsecutivo");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoLessThan(Short value) {
            addCriterion("id_consecutivo <", value, "idConsecutivo");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoLessThanOrEqualTo(Short value) {
            addCriterion("id_consecutivo <=", value, "idConsecutivo");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoIn(List<Short> values) {
            addCriterion("id_consecutivo in", values, "idConsecutivo");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoNotIn(List<Short> values) {
            addCriterion("id_consecutivo not in", values, "idConsecutivo");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoBetween(Short value1, Short value2) {
            addCriterion("id_consecutivo between", value1, value2, "idConsecutivo");
            return (Criteria) this;
        }

        public Criteria andIdConsecutivoNotBetween(Short value1, Short value2) {
            addCriterion("id_consecutivo not between", value1, value2, "idConsecutivo");
            return (Criteria) this;
        }

        public Criteria andAccion1IsNull() {
            addCriterion("accion1 is null");
            return (Criteria) this;
        }

        public Criteria andAccion1IsNotNull() {
            addCriterion("accion1 is not null");
            return (Criteria) this;
        }

        public Criteria andAccion1EqualTo(String value) {
            addCriterion("accion1 =", value, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion1NotEqualTo(String value) {
            addCriterion("accion1 <>", value, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion1GreaterThan(String value) {
            addCriterion("accion1 >", value, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion1GreaterThanOrEqualTo(String value) {
            addCriterion("accion1 >=", value, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion1LessThan(String value) {
            addCriterion("accion1 <", value, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion1LessThanOrEqualTo(String value) {
            addCriterion("accion1 <=", value, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion1Like(String value) {
            addCriterion("accion1 like", value, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion1NotLike(String value) {
            addCriterion("accion1 not like", value, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion1In(List<String> values) {
            addCriterion("accion1 in", values, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion1NotIn(List<String> values) {
            addCriterion("accion1 not in", values, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion1Between(String value1, String value2) {
            addCriterion("accion1 between", value1, value2, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion1NotBetween(String value1, String value2) {
            addCriterion("accion1 not between", value1, value2, "accion1");
            return (Criteria) this;
        }

        public Criteria andAccion2IsNull() {
            addCriterion("accion2 is null");
            return (Criteria) this;
        }

        public Criteria andAccion2IsNotNull() {
            addCriterion("accion2 is not null");
            return (Criteria) this;
        }

        public Criteria andAccion2EqualTo(String value) {
            addCriterion("accion2 =", value, "accion2");
            return (Criteria) this;
        }

        public Criteria andAccion2NotEqualTo(String value) {
            addCriterion("accion2 <>", value, "accion2");
            return (Criteria) this;
        }

        public Criteria andAccion2GreaterThan(String value) {
            addCriterion("accion2 >", value, "accion2");
            return (Criteria) this;
        }

        public Criteria andAccion2GreaterThanOrEqualTo(String value) {
            addCriterion("accion2 >=", value, "accion2");
            return (Criteria) this;
        }

        public Criteria andAccion2LessThan(String value) {
            addCriterion("accion2 <", value, "accion2");
            return (Criteria) this;
        }

        public Criteria andAccion2LessThanOrEqualTo(String value) {
            addCriterion("accion2 <=", value, "accion2");
            return (Criteria) this;
        }

        public Criteria andAccion2Like(String value) {
            addCriterion("accion2 like", value, "accion2");
            return (Criteria) this;
        }

        public Criteria andAccion2NotLike(String value) {
            addCriterion("accion2 not like", value, "accion2");
            return (Criteria) this;
        }

        public Criteria andAccion2In(List<String> values) {
            addCriterion("accion2 in", values, "accion2");
            return (Criteria) this;
        }

        public Criteria andAccion2NotIn(List<String> values) {
            addCriterion("accion2 not in", values, "accion2");
            return (Criteria) this;
        }

        public Criteria andAccion2Between(String value1, String value2) {
            addCriterion("accion2 between", value1, value2, "accion2");
            return (Criteria) this;
        }

        public Criteria andAccion2NotBetween(String value1, String value2) {
            addCriterion("accion2 not between", value1, value2, "accion2");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoIsNull() {
            addCriterion("nom_otro_compromiso is null");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoIsNotNull() {
            addCriterion("nom_otro_compromiso is not null");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoEqualTo(String value) {
            addCriterion("nom_otro_compromiso =", value, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoNotEqualTo(String value) {
            addCriterion("nom_otro_compromiso <>", value, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoGreaterThan(String value) {
            addCriterion("nom_otro_compromiso >", value, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoGreaterThanOrEqualTo(String value) {
            addCriterion("nom_otro_compromiso >=", value, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoLessThan(String value) {
            addCriterion("nom_otro_compromiso <", value, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoLessThanOrEqualTo(String value) {
            addCriterion("nom_otro_compromiso <=", value, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoLike(String value) {
            addCriterion("nom_otro_compromiso like", value, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoNotLike(String value) {
            addCriterion("nom_otro_compromiso not like", value, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoIn(List<String> values) {
            addCriterion("nom_otro_compromiso in", values, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoNotIn(List<String> values) {
            addCriterion("nom_otro_compromiso not in", values, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoBetween(String value1, String value2) {
            addCriterion("nom_otro_compromiso between", value1, value2, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andNomOtroCompromisoNotBetween(String value1, String value2) {
            addCriterion("nom_otro_compromiso not between", value1, value2, "nomOtroCompromiso");
            return (Criteria) this;
        }

        public Criteria andCumplimientoIsNull() {
            addCriterion("cumplimiento is null");
            return (Criteria) this;
        }

        public Criteria andCumplimientoIsNotNull() {
            addCriterion("cumplimiento is not null");
            return (Criteria) this;
        }

        public Criteria andCumplimientoEqualTo(Short value) {
            addCriterion("cumplimiento =", value, "cumplimiento");
            return (Criteria) this;
        }

        public Criteria andCumplimientoNotEqualTo(Short value) {
            addCriterion("cumplimiento <>", value, "cumplimiento");
            return (Criteria) this;
        }

        public Criteria andCumplimientoGreaterThan(Short value) {
            addCriterion("cumplimiento >", value, "cumplimiento");
            return (Criteria) this;
        }

        public Criteria andCumplimientoGreaterThanOrEqualTo(Short value) {
            addCriterion("cumplimiento >=", value, "cumplimiento");
            return (Criteria) this;
        }

        public Criteria andCumplimientoLessThan(Short value) {
            addCriterion("cumplimiento <", value, "cumplimiento");
            return (Criteria) this;
        }

        public Criteria andCumplimientoLessThanOrEqualTo(Short value) {
            addCriterion("cumplimiento <=", value, "cumplimiento");
            return (Criteria) this;
        }

        public Criteria andCumplimientoIn(List<Short> values) {
            addCriterion("cumplimiento in", values, "cumplimiento");
            return (Criteria) this;
        }

        public Criteria andCumplimientoNotIn(List<Short> values) {
            addCriterion("cumplimiento not in", values, "cumplimiento");
            return (Criteria) this;
        }

        public Criteria andCumplimientoBetween(Short value1, Short value2) {
            addCriterion("cumplimiento between", value1, value2, "cumplimiento");
            return (Criteria) this;
        }

        public Criteria andCumplimientoNotBetween(Short value1, Short value2) {
            addCriterion("cumplimiento not between", value1, value2, "cumplimiento");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ce_compromisos
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 11 11:07:26 CDT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Jun 11 11:07:26 CDT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}