package mx.gob.sep.dgtec.repuce.model;

public class CeComites {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.c_cct
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private Integer cCct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.c_sesion
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private Short cSesion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.ce_comites
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private Integer ceComites;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.id_comite
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private Integer idComite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.nom_comite
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private String nomComite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.num_integrantes
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private Short numIntegrantes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.nom_presidente
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private String nomPresidente;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.id_calidad
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private Integer idCalidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.nomcalidad
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private String nomcalidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.id_acuerdo
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private Integer idAcuerdo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.acuerdo
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private String acuerdo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites.nom_otro_comite
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    private String nomOtroComite;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.c_cct
     *
     * @return the value of ce_comites.c_cct
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public Integer getcCct() {
        return cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.c_cct
     *
     * @param cCct the value for ce_comites.c_cct
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setcCct(Integer cCct) {
        this.cCct = cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.c_sesion
     *
     * @return the value of ce_comites.c_sesion
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public Short getcSesion() {
        return cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.c_sesion
     *
     * @param cSesion the value for ce_comites.c_sesion
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setcSesion(Short cSesion) {
        this.cSesion = cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.ce_comites
     *
     * @return the value of ce_comites.ce_comites
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public Integer getCeComites() {
        return ceComites;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.ce_comites
     *
     * @param ceComites the value for ce_comites.ce_comites
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setCeComites(Integer ceComites) {
        this.ceComites = ceComites;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.id_comite
     *
     * @return the value of ce_comites.id_comite
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public Integer getIdComite() {
        return idComite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.id_comite
     *
     * @param idComite the value for ce_comites.id_comite
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setIdComite(Integer idComite) {
        this.idComite = idComite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.nom_comite
     *
     * @return the value of ce_comites.nom_comite
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public String getNomComite() {
        return nomComite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.nom_comite
     *
     * @param nomComite the value for ce_comites.nom_comite
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setNomComite(String nomComite) {
        this.nomComite = nomComite == null ? null : nomComite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.num_integrantes
     *
     * @return the value of ce_comites.num_integrantes
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public Short getNumIntegrantes() {
        return numIntegrantes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.num_integrantes
     *
     * @param numIntegrantes the value for ce_comites.num_integrantes
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setNumIntegrantes(Short numIntegrantes) {
        this.numIntegrantes = numIntegrantes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.nom_presidente
     *
     * @return the value of ce_comites.nom_presidente
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public String getNomPresidente() {
        return nomPresidente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.nom_presidente
     *
     * @param nomPresidente the value for ce_comites.nom_presidente
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setNomPresidente(String nomPresidente) {
        this.nomPresidente = nomPresidente == null ? null : nomPresidente.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.id_calidad
     *
     * @return the value of ce_comites.id_calidad
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public Integer getIdCalidad() {
        return idCalidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.id_calidad
     *
     * @param idCalidad the value for ce_comites.id_calidad
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setIdCalidad(Integer idCalidad) {
        this.idCalidad = idCalidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.nomcalidad
     *
     * @return the value of ce_comites.nomcalidad
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public String getNomcalidad() {
        return nomcalidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.nomcalidad
     *
     * @param nomcalidad the value for ce_comites.nomcalidad
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setNomcalidad(String nomcalidad) {
        this.nomcalidad = nomcalidad == null ? null : nomcalidad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.id_acuerdo
     *
     * @return the value of ce_comites.id_acuerdo
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public Integer getIdAcuerdo() {
        return idAcuerdo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.id_acuerdo
     *
     * @param idAcuerdo the value for ce_comites.id_acuerdo
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setIdAcuerdo(Integer idAcuerdo) {
        this.idAcuerdo = idAcuerdo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.acuerdo
     *
     * @return the value of ce_comites.acuerdo
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public String getAcuerdo() {
        return acuerdo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.acuerdo
     *
     * @param acuerdo the value for ce_comites.acuerdo
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setAcuerdo(String acuerdo) {
        this.acuerdo = acuerdo == null ? null : acuerdo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites.nom_otro_comite
     *
     * @return the value of ce_comites.nom_otro_comite
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public String getNomOtroComite() {
        return nomOtroComite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites.nom_otro_comite
     *
     * @param nomOtroComite the value for ce_comites.nom_otro_comite
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    public void setNomOtroComite(String nomOtroComite) {
        this.nomOtroComite = nomOtroComite == null ? null : nomOtroComite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CeComites other = (CeComites) that;
        return (this.getcCct() == null ? other.getcCct() == null : this.getcCct().equals(other.getcCct()))
            && (this.getcSesion() == null ? other.getcSesion() == null : this.getcSesion().equals(other.getcSesion()))
            && (this.getCeComites() == null ? other.getCeComites() == null : this.getCeComites().equals(other.getCeComites()))
            && (this.getIdComite() == null ? other.getIdComite() == null : this.getIdComite().equals(other.getIdComite()))
            && (this.getNomComite() == null ? other.getNomComite() == null : this.getNomComite().equals(other.getNomComite()))
            && (this.getNumIntegrantes() == null ? other.getNumIntegrantes() == null : this.getNumIntegrantes().equals(other.getNumIntegrantes()))
            && (this.getNomPresidente() == null ? other.getNomPresidente() == null : this.getNomPresidente().equals(other.getNomPresidente()))
            && (this.getIdCalidad() == null ? other.getIdCalidad() == null : this.getIdCalidad().equals(other.getIdCalidad()))
            && (this.getNomcalidad() == null ? other.getNomcalidad() == null : this.getNomcalidad().equals(other.getNomcalidad()))
            && (this.getIdAcuerdo() == null ? other.getIdAcuerdo() == null : this.getIdAcuerdo().equals(other.getIdAcuerdo()))
            && (this.getAcuerdo() == null ? other.getAcuerdo() == null : this.getAcuerdo().equals(other.getAcuerdo()))
            && (this.getNomOtroComite() == null ? other.getNomOtroComite() == null : this.getNomOtroComite().equals(other.getNomOtroComite()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites
     *
     * @mbggenerated Tue Sep 23 14:59:01 CDT 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcCct() == null) ? 0 : getcCct().hashCode());
        result = prime * result + ((getcSesion() == null) ? 0 : getcSesion().hashCode());
        result = prime * result + ((getCeComites() == null) ? 0 : getCeComites().hashCode());
        result = prime * result + ((getIdComite() == null) ? 0 : getIdComite().hashCode());
        result = prime * result + ((getNomComite() == null) ? 0 : getNomComite().hashCode());
        result = prime * result + ((getNumIntegrantes() == null) ? 0 : getNumIntegrantes().hashCode());
        result = prime * result + ((getNomPresidente() == null) ? 0 : getNomPresidente().hashCode());
        result = prime * result + ((getIdCalidad() == null) ? 0 : getIdCalidad().hashCode());
        result = prime * result + ((getNomcalidad() == null) ? 0 : getNomcalidad().hashCode());
        result = prime * result + ((getIdAcuerdo() == null) ? 0 : getIdAcuerdo().hashCode());
        result = prime * result + ((getAcuerdo() == null) ? 0 : getAcuerdo().hashCode());
        result = prime * result + ((getNomOtroComite() == null) ? 0 : getNomOtroComite().hashCode());
        return result;
    }
}