package mx.gob.sep.dgtec.repuce.model;

public class CeCompromisosCstm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_compromisos.c_cct
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    private Integer cCct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_compromisos.c_sesion
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    private Short cSesion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_compromisos.id_compromiso
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    private Short idCompromiso;
    
    private String compromiso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_compromisos.id_consecutivo
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    private Short idConsecutivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_compromisos.accion1
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    private String accion1;
    private String accion2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_compromisos.nom_otro_compromiso
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    private String nomOtroCompromiso;

    
    private Short cumplimiento;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_compromisos.c_cct
     *
     * @return the value of ce_compromisos.c_cct
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public Integer getcCct() {
        return cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_compromisos.c_cct
     *
     * @param cCct the value for ce_compromisos.c_cct
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public void setcCct(Integer cCct) {
        this.cCct = cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_compromisos.c_sesion
     *
     * @return the value of ce_compromisos.c_sesion
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public Short getcSesion() {
        return cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_compromisos.c_sesion
     *
     * @param cSesion the value for ce_compromisos.c_sesion
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public void setcSesion(Short cSesion) {
        this.cSesion = cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_compromisos.id_compromiso
     *
     * @return the value of ce_compromisos.id_compromiso
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public Short getIdCompromiso() {
        return idCompromiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_compromisos.id_compromiso
     *
     * @param idCompromiso the value for ce_compromisos.id_compromiso
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public void setIdCompromiso(Short idCompromiso) {
        this.idCompromiso = idCompromiso;
    }
        
    public String getCompromiso() {
		return compromiso;
	}

	public void setCompromiso(String compromiso) {
		this.compromiso = compromiso;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_compromisos.id_consecutivo
     *
     * @return the value of ce_compromisos.id_consecutivo
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public Short getIdConsecutivo() {
        return idConsecutivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_compromisos.id_consecutivo
     *
     * @param idConsecutivo the value for ce_compromisos.id_consecutivo
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public void setIdConsecutivo(Short idConsecutivo) {
        this.idConsecutivo = idConsecutivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_compromisos.accion1
     *
     * @return the value of ce_compromisos.accion1
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public String getAccion1() {
        return accion1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_compromisos.accion1
     *
     * @param accion1 the value for ce_compromisos.accion1
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public void setAccion1(String accion1) {
        this.accion1 = accion1 == null ? null : accion1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_compromisos.nom_otro_compromiso
     *
     * @return the value of ce_compromisos.nom_otro_compromiso
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public String getNomOtroCompromiso() {
        return nomOtroCompromiso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_compromisos.nom_otro_compromiso
     *
     * @param nomOtroCompromiso the value for ce_compromisos.nom_otro_compromiso
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    public void setNomOtroCompromiso(String nomOtroCompromiso) {
        this.nomOtroCompromiso = nomOtroCompromiso == null ? null : nomOtroCompromiso.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    
    
    
    
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CeCompromisosCstm other = (CeCompromisosCstm) that;
        return (this.getcCct() == null ? other.getcCct() == null : this.getcCct().equals(other.getcCct()))
            && (this.getcSesion() == null ? other.getcSesion() == null : this.getcSesion().equals(other.getcSesion()))
            && (this.getIdCompromiso() == null ? other.getIdCompromiso() == null : this.getIdCompromiso().equals(other.getIdCompromiso()))
            && (this.getIdConsecutivo() == null ? other.getIdConsecutivo() == null : this.getIdConsecutivo().equals(other.getIdConsecutivo()))
            && (this.getAccion1() == null ? other.getAccion1() == null : this.getAccion1().equals(other.getAccion1()))
            && (this.getNomOtroCompromiso() == null ? other.getNomOtroCompromiso() == null : this.getNomOtroCompromiso().equals(other.getNomOtroCompromiso()))
            && (this.getCumplimiento() == null ? other.getCumplimiento() == null : this.getCumplimiento().equals(other.getCumplimiento()));
    }

    public Short getCumplimiento() {
		return cumplimiento;
	}

	public void setCumplimiento(Short cumplimiento) {
		this.cumplimiento = cumplimiento;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_compromisos
     *
     * @mbggenerated Thu Nov 06 17:34:56 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcCct() == null) ? 0 : getcCct().hashCode());
        result = prime * result + ((getcSesion() == null) ? 0 : getcSesion().hashCode());
        result = prime * result + ((getIdCompromiso() == null) ? 0 : getIdCompromiso().hashCode());
        result = prime * result + ((getIdConsecutivo() == null) ? 0 : getIdConsecutivo().hashCode());
        result = prime * result + ((getAccion1() == null) ? 0 : getAccion1().hashCode());
        result = prime * result + ((getNomOtroCompromiso() == null) ? 0 : getNomOtroCompromiso().hashCode());
        result = prime * result + ((getCumplimiento() == null) ? 0 : getCumplimiento().hashCode());        
        return result;
    }

	public String getAccion2() {
		return accion2;
	}

	public void setAccion2(String accion2) {
		this.accion2 = accion2;
	}
}