package mx.gob.sep.dgtec.repuce.model;

public class CeComitesSeguimiento {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites_seguimiento.c_cct
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private Integer cCct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites_seguimiento.c_sesion
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private Short cSesion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites_seguimiento.id_comite
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private Integer idComite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites_seguimiento.accion1
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private String accion1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites_seguimiento.accion2
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private String accion2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites_seguimiento.accion3
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private String accion3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites_seguimiento.accion4
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private String accion4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites_seguimiento.accion5
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private String accion5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comites_seguimiento.actividad_comite1
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private Integer actividadComite1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites_seguimiento.c_cct
     *
     * @return the value of ce_comites_seguimiento.c_cct
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public Integer getcCct() {
        return cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites_seguimiento.c_cct
     *
     * @param cCct the value for ce_comites_seguimiento.c_cct
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setcCct(Integer cCct) {
        this.cCct = cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites_seguimiento.c_sesion
     *
     * @return the value of ce_comites_seguimiento.c_sesion
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public Short getcSesion() {
        return cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites_seguimiento.c_sesion
     *
     * @param cSesion the value for ce_comites_seguimiento.c_sesion
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setcSesion(Short cSesion) {
        this.cSesion = cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites_seguimiento.id_comite
     *
     * @return the value of ce_comites_seguimiento.id_comite
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public Integer getIdComite() {
        return idComite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites_seguimiento.id_comite
     *
     * @param idComite the value for ce_comites_seguimiento.id_comite
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setIdComite(Integer idComite) {
        this.idComite = idComite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites_seguimiento.accion1
     *
     * @return the value of ce_comites_seguimiento.accion1
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public String getAccion1() {
        return accion1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites_seguimiento.accion1
     *
     * @param accion1 the value for ce_comites_seguimiento.accion1
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setAccion1(String accion1) {
        this.accion1 = accion1 == null ? null : accion1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites_seguimiento.accion2
     *
     * @return the value of ce_comites_seguimiento.accion2
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public String getAccion2() {
        return accion2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites_seguimiento.accion2
     *
     * @param accion2 the value for ce_comites_seguimiento.accion2
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setAccion2(String accion2) {
        this.accion2 = accion2 == null ? null : accion2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites_seguimiento.accion3
     *
     * @return the value of ce_comites_seguimiento.accion3
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public String getAccion3() {
        return accion3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites_seguimiento.accion3
     *
     * @param accion3 the value for ce_comites_seguimiento.accion3
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setAccion3(String accion3) {
        this.accion3 = accion3 == null ? null : accion3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites_seguimiento.accion4
     *
     * @return the value of ce_comites_seguimiento.accion4
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public String getAccion4() {
        return accion4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites_seguimiento.accion4
     *
     * @param accion4 the value for ce_comites_seguimiento.accion4
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setAccion4(String accion4) {
        this.accion4 = accion4 == null ? null : accion4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites_seguimiento.accion5
     *
     * @return the value of ce_comites_seguimiento.accion5
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public String getAccion5() {
        return accion5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites_seguimiento.accion5
     *
     * @param accion5 the value for ce_comites_seguimiento.accion5
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setAccion5(String accion5) {
        this.accion5 = accion5 == null ? null : accion5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comites_seguimiento.actividad_comite1
     *
     * @return the value of ce_comites_seguimiento.actividad_comite1
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public Integer getActividadComite1() {
        return actividadComite1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comites_seguimiento.actividad_comite1
     *
     * @param actividadComite1 the value for ce_comites_seguimiento.actividad_comite1
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setActividadComite1(Integer actividadComite1) {
        this.actividadComite1 = actividadComite1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CeComitesSeguimiento other = (CeComitesSeguimiento) that;
        return (this.getcCct() == null ? other.getcCct() == null : this.getcCct().equals(other.getcCct()))
            && (this.getcSesion() == null ? other.getcSesion() == null : this.getcSesion().equals(other.getcSesion()))
            && (this.getIdComite() == null ? other.getIdComite() == null : this.getIdComite().equals(other.getIdComite()))
            && (this.getAccion1() == null ? other.getAccion1() == null : this.getAccion1().equals(other.getAccion1()))
            && (this.getAccion2() == null ? other.getAccion2() == null : this.getAccion2().equals(other.getAccion2()))
            && (this.getAccion3() == null ? other.getAccion3() == null : this.getAccion3().equals(other.getAccion3()))
            && (this.getAccion4() == null ? other.getAccion4() == null : this.getAccion4().equals(other.getAccion4()))
            && (this.getAccion5() == null ? other.getAccion5() == null : this.getAccion5().equals(other.getAccion5()))
            && (this.getActividadComite1() == null ? other.getActividadComite1() == null : this.getActividadComite1().equals(other.getActividadComite1()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comites_seguimiento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcCct() == null) ? 0 : getcCct().hashCode());
        result = prime * result + ((getcSesion() == null) ? 0 : getcSesion().hashCode());
        result = prime * result + ((getIdComite() == null) ? 0 : getIdComite().hashCode());
        result = prime * result + ((getAccion1() == null) ? 0 : getAccion1().hashCode());
        result = prime * result + ((getAccion2() == null) ? 0 : getAccion2().hashCode());
        result = prime * result + ((getAccion3() == null) ? 0 : getAccion3().hashCode());
        result = prime * result + ((getAccion4() == null) ? 0 : getAccion4().hashCode());
        result = prime * result + ((getAccion5() == null) ? 0 : getAccion5().hashCode());
        result = prime * result + ((getActividadComite1() == null) ? 0 : getActividadComite1().hashCode());
        return result;
    }
}