package mx.gob.sep.dgtec.repuce.model;

public class CeCompEnlace {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comp_enlace.c_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Integer cCct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comp_enlace.c_sesion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Short cSesion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comp_enlace.c_comp_enlace
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Short cCompEnlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comp_enlace.nom_otro_comp
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String nomOtroComp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comp_enlace.c_cct
     *
     * @return the value of ce_comp_enlace.c_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Integer getcCct() {
        return cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comp_enlace.c_cct
     *
     * @param cCct the value for ce_comp_enlace.c_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setcCct(Integer cCct) {
        this.cCct = cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comp_enlace.c_sesion
     *
     * @return the value of ce_comp_enlace.c_sesion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Short getcSesion() {
        return cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comp_enlace.c_sesion
     *
     * @param cSesion the value for ce_comp_enlace.c_sesion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setcSesion(Short cSesion) {
        this.cSesion = cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comp_enlace.c_comp_enlace
     *
     * @return the value of ce_comp_enlace.c_comp_enlace
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Short getcCompEnlace() {
        return cCompEnlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comp_enlace.c_comp_enlace
     *
     * @param cCompEnlace the value for ce_comp_enlace.c_comp_enlace
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setcCompEnlace(Short cCompEnlace) {
        this.cCompEnlace = cCompEnlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comp_enlace.nom_otro_comp
     *
     * @return the value of ce_comp_enlace.nom_otro_comp
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getNomOtroComp() {
        return nomOtroComp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comp_enlace.nom_otro_comp
     *
     * @param nomOtroComp the value for ce_comp_enlace.nom_otro_comp
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setNomOtroComp(String nomOtroComp) {
        this.nomOtroComp = nomOtroComp == null ? null : nomOtroComp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comp_enlace
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CeCompEnlace other = (CeCompEnlace) that;
        return (this.getcCct() == null ? other.getcCct() == null : this.getcCct().equals(other.getcCct()))
            && (this.getcSesion() == null ? other.getcSesion() == null : this.getcSesion().equals(other.getcSesion()))
            && (this.getcCompEnlace() == null ? other.getcCompEnlace() == null : this.getcCompEnlace().equals(other.getcCompEnlace()))
            && (this.getNomOtroComp() == null ? other.getNomOtroComp() == null : this.getNomOtroComp().equals(other.getNomOtroComp()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comp_enlace
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcCct() == null) ? 0 : getcCct().hashCode());
        result = prime * result + ((getcSesion() == null) ? 0 : getcSesion().hashCode());
        result = prime * result + ((getcCompEnlace() == null) ? 0 : getcCompEnlace().hashCode());
        result = prime * result + ((getNomOtroComp() == null) ? 0 : getNomOtroComp().hashCode());
        return result;
    }
}