package mx.gob.sep.dgtec.repuce.model;

public class CeComiteIntegrante {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comite_integrante.ce_integrante_comite_c_cct
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    private Integer ceIntegranteComiteCCct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comite_integrante.ce_integrante_comite_c_sesion
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    private Short ceIntegranteComiteCSesion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comite_integrante.ce_integrante_comite_csc_integrante
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    private Short ceIntegranteComiteCscIntegrante;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comite_integrante.ce_comite_c_cct
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    private Integer ceComiteCCct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comite_integrante.ce_comite_c_sesion
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    private Short ceComiteCSesion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_comite_integrante.ce_comite_c_comite
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    private Integer ceComiteCComite;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comite_integrante.ce_integrante_comite_c_cct
     *
     * @return the value of ce_comite_integrante.ce_integrante_comite_c_cct
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public Integer getCeIntegranteComiteCCct() {
        return ceIntegranteComiteCCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comite_integrante.ce_integrante_comite_c_cct
     *
     * @param ceIntegranteComiteCCct the value for ce_comite_integrante.ce_integrante_comite_c_cct
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public void setCeIntegranteComiteCCct(Integer ceIntegranteComiteCCct) {
        this.ceIntegranteComiteCCct = ceIntegranteComiteCCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comite_integrante.ce_integrante_comite_c_sesion
     *
     * @return the value of ce_comite_integrante.ce_integrante_comite_c_sesion
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public Short getCeIntegranteComiteCSesion() {
        return ceIntegranteComiteCSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comite_integrante.ce_integrante_comite_c_sesion
     *
     * @param ceIntegranteComiteCSesion the value for ce_comite_integrante.ce_integrante_comite_c_sesion
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public void setCeIntegranteComiteCSesion(Short ceIntegranteComiteCSesion) {
        this.ceIntegranteComiteCSesion = ceIntegranteComiteCSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comite_integrante.ce_integrante_comite_csc_integrante
     *
     * @return the value of ce_comite_integrante.ce_integrante_comite_csc_integrante
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public Short getCeIntegranteComiteCscIntegrante() {
        return ceIntegranteComiteCscIntegrante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comite_integrante.ce_integrante_comite_csc_integrante
     *
     * @param ceIntegranteComiteCscIntegrante the value for ce_comite_integrante.ce_integrante_comite_csc_integrante
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public void setCeIntegranteComiteCscIntegrante(Short ceIntegranteComiteCscIntegrante) {
        this.ceIntegranteComiteCscIntegrante = ceIntegranteComiteCscIntegrante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comite_integrante.ce_comite_c_cct
     *
     * @return the value of ce_comite_integrante.ce_comite_c_cct
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public Integer getCeComiteCCct() {
        return ceComiteCCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comite_integrante.ce_comite_c_cct
     *
     * @param ceComiteCCct the value for ce_comite_integrante.ce_comite_c_cct
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public void setCeComiteCCct(Integer ceComiteCCct) {
        this.ceComiteCCct = ceComiteCCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comite_integrante.ce_comite_c_sesion
     *
     * @return the value of ce_comite_integrante.ce_comite_c_sesion
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public Short getCeComiteCSesion() {
        return ceComiteCSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comite_integrante.ce_comite_c_sesion
     *
     * @param ceComiteCSesion the value for ce_comite_integrante.ce_comite_c_sesion
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public void setCeComiteCSesion(Short ceComiteCSesion) {
        this.ceComiteCSesion = ceComiteCSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_comite_integrante.ce_comite_c_comite
     *
     * @return the value of ce_comite_integrante.ce_comite_c_comite
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public Integer getCeComiteCComite() {
        return ceComiteCComite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_comite_integrante.ce_comite_c_comite
     *
     * @param ceComiteCComite the value for ce_comite_integrante.ce_comite_c_comite
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    public void setCeComiteCComite(Integer ceComiteCComite) {
        this.ceComiteCComite = ceComiteCComite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comite_integrante
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CeComiteIntegrante other = (CeComiteIntegrante) that;
        return (this.getCeIntegranteComiteCCct() == null ? other.getCeIntegranteComiteCCct() == null : this.getCeIntegranteComiteCCct().equals(other.getCeIntegranteComiteCCct()))
            && (this.getCeIntegranteComiteCSesion() == null ? other.getCeIntegranteComiteCSesion() == null : this.getCeIntegranteComiteCSesion().equals(other.getCeIntegranteComiteCSesion()))
            && (this.getCeIntegranteComiteCscIntegrante() == null ? other.getCeIntegranteComiteCscIntegrante() == null : this.getCeIntegranteComiteCscIntegrante().equals(other.getCeIntegranteComiteCscIntegrante()))
            && (this.getCeComiteCCct() == null ? other.getCeComiteCCct() == null : this.getCeComiteCCct().equals(other.getCeComiteCCct()))
            && (this.getCeComiteCSesion() == null ? other.getCeComiteCSesion() == null : this.getCeComiteCSesion().equals(other.getCeComiteCSesion()))
            && (this.getCeComiteCComite() == null ? other.getCeComiteCComite() == null : this.getCeComiteCComite().equals(other.getCeComiteCComite()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_comite_integrante
     *
     * @mbggenerated Mon Aug 12 12:10:46 CDT 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCeIntegranteComiteCCct() == null) ? 0 : getCeIntegranteComiteCCct().hashCode());
        result = prime * result + ((getCeIntegranteComiteCSesion() == null) ? 0 : getCeIntegranteComiteCSesion().hashCode());
        result = prime * result + ((getCeIntegranteComiteCscIntegrante() == null) ? 0 : getCeIntegranteComiteCscIntegrante().hashCode());
        result = prime * result + ((getCeComiteCCct() == null) ? 0 : getCeComiteCCct().hashCode());
        result = prime * result + ((getCeComiteCSesion() == null) ? 0 : getCeComiteCSesion().hashCode());
        result = prime * result + ((getCeComiteCComite() == null) ? 0 : getCeComiteCComite().hashCode());
        return result;
    }
}