package mx.gob.sep.dgtec.repuce.model;

import java.math.BigDecimal;

public class CeEventos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.c_cct
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private Integer cCct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.c_sesion
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private Short cSesion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.c_evento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private Integer cEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.fecha_horarios_programados
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private String fechaHorariosProgramados;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.fuente_recursos
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private Integer fuenteRecursos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.nom_otro_evento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private String nomOtroEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.nom_otro_fr
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private String nomOtroFr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.cumplio_evento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private Integer cumplioEvento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.monto_r
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private BigDecimal montoR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.monto_str_r
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private String montoStrR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.monto_g
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private BigDecimal montoG;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_eventos.monto_str_g
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    private String montoStrG;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.c_cct
     *
     * @return the value of ce_eventos.c_cct
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public Integer getcCct() {
        return cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.c_cct
     *
     * @param cCct the value for ce_eventos.c_cct
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setcCct(Integer cCct) {
        this.cCct = cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.c_sesion
     *
     * @return the value of ce_eventos.c_sesion
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public Short getcSesion() {
        return cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.c_sesion
     *
     * @param cSesion the value for ce_eventos.c_sesion
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setcSesion(Short cSesion) {
        this.cSesion = cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.c_evento
     *
     * @return the value of ce_eventos.c_evento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public Integer getcEvento() {
        return cEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.c_evento
     *
     * @param cEvento the value for ce_eventos.c_evento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setcEvento(Integer cEvento) {
        this.cEvento = cEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.fecha_horarios_programados
     *
     * @return the value of ce_eventos.fecha_horarios_programados
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public String getFechaHorariosProgramados() {
        return fechaHorariosProgramados;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.fecha_horarios_programados
     *
     * @param fechaHorariosProgramados the value for ce_eventos.fecha_horarios_programados
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setFechaHorariosProgramados(String fechaHorariosProgramados) {
        this.fechaHorariosProgramados = fechaHorariosProgramados == null ? null : fechaHorariosProgramados.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.fuente_recursos
     *
     * @return the value of ce_eventos.fuente_recursos
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public Integer getFuenteRecursos() {
        return fuenteRecursos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.fuente_recursos
     *
     * @param fuenteRecursos the value for ce_eventos.fuente_recursos
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setFuenteRecursos(Integer fuenteRecursos) {
        this.fuenteRecursos = fuenteRecursos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.nom_otro_evento
     *
     * @return the value of ce_eventos.nom_otro_evento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public String getNomOtroEvento() {
        return nomOtroEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.nom_otro_evento
     *
     * @param nomOtroEvento the value for ce_eventos.nom_otro_evento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setNomOtroEvento(String nomOtroEvento) {
        this.nomOtroEvento = nomOtroEvento == null ? null : nomOtroEvento.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.nom_otro_fr
     *
     * @return the value of ce_eventos.nom_otro_fr
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public String getNomOtroFr() {
        return nomOtroFr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.nom_otro_fr
     *
     * @param nomOtroFr the value for ce_eventos.nom_otro_fr
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setNomOtroFr(String nomOtroFr) {
        this.nomOtroFr = nomOtroFr == null ? null : nomOtroFr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.cumplio_evento
     *
     * @return the value of ce_eventos.cumplio_evento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public Integer getCumplioEvento() {
        return cumplioEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.cumplio_evento
     *
     * @param cumplioEvento the value for ce_eventos.cumplio_evento
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setCumplioEvento(Integer cumplioEvento) {
        this.cumplioEvento = cumplioEvento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.monto_r
     *
     * @return the value of ce_eventos.monto_r
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public BigDecimal getMontoR() {
        return montoR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.monto_r
     *
     * @param montoR the value for ce_eventos.monto_r
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setMontoR(BigDecimal montoR) {
        this.montoR = montoR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.monto_str_r
     *
     * @return the value of ce_eventos.monto_str_r
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public String getMontoStrR() {
        return montoStrR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.monto_str_r
     *
     * @param montoStrR the value for ce_eventos.monto_str_r
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setMontoStrR(String montoStrR) {
        this.montoStrR = montoStrR == null ? null : montoStrR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.monto_g
     *
     * @return the value of ce_eventos.monto_g
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public BigDecimal getMontoG() {
        return montoG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.monto_g
     *
     * @param montoG the value for ce_eventos.monto_g
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setMontoG(BigDecimal montoG) {
        this.montoG = montoG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_eventos.monto_str_g
     *
     * @return the value of ce_eventos.monto_str_g
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public String getMontoStrG() {
        return montoStrG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_eventos.monto_str_g
     *
     * @param montoStrG the value for ce_eventos.monto_str_g
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    public void setMontoStrG(String montoStrG) {
        this.montoStrG = montoStrG == null ? null : montoStrG.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_eventos
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CeEventos other = (CeEventos) that;
        return (this.getcCct() == null ? other.getcCct() == null : this.getcCct().equals(other.getcCct()))
            && (this.getcSesion() == null ? other.getcSesion() == null : this.getcSesion().equals(other.getcSesion()))
            && (this.getcEvento() == null ? other.getcEvento() == null : this.getcEvento().equals(other.getcEvento()))
            && (this.getFechaHorariosProgramados() == null ? other.getFechaHorariosProgramados() == null : this.getFechaHorariosProgramados().equals(other.getFechaHorariosProgramados()))
            && (this.getFuenteRecursos() == null ? other.getFuenteRecursos() == null : this.getFuenteRecursos().equals(other.getFuenteRecursos()))
            && (this.getNomOtroEvento() == null ? other.getNomOtroEvento() == null : this.getNomOtroEvento().equals(other.getNomOtroEvento()))
            && (this.getNomOtroFr() == null ? other.getNomOtroFr() == null : this.getNomOtroFr().equals(other.getNomOtroFr()))
            && (this.getCumplioEvento() == null ? other.getCumplioEvento() == null : this.getCumplioEvento().equals(other.getCumplioEvento()))
            && (this.getMontoR() == null ? other.getMontoR() == null : this.getMontoR().equals(other.getMontoR()))
            && (this.getMontoStrR() == null ? other.getMontoStrR() == null : this.getMontoStrR().equals(other.getMontoStrR()))
            && (this.getMontoG() == null ? other.getMontoG() == null : this.getMontoG().equals(other.getMontoG()))
            && (this.getMontoStrG() == null ? other.getMontoStrG() == null : this.getMontoStrG().equals(other.getMontoStrG()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_eventos
     *
     * @mbggenerated Thu Jun 04 14:27:33 CDT 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcCct() == null) ? 0 : getcCct().hashCode());
        result = prime * result + ((getcSesion() == null) ? 0 : getcSesion().hashCode());
        result = prime * result + ((getcEvento() == null) ? 0 : getcEvento().hashCode());
        result = prime * result + ((getFechaHorariosProgramados() == null) ? 0 : getFechaHorariosProgramados().hashCode());
        result = prime * result + ((getFuenteRecursos() == null) ? 0 : getFuenteRecursos().hashCode());
        result = prime * result + ((getNomOtroEvento() == null) ? 0 : getNomOtroEvento().hashCode());
        result = prime * result + ((getNomOtroFr() == null) ? 0 : getNomOtroFr().hashCode());
        result = prime * result + ((getCumplioEvento() == null) ? 0 : getCumplioEvento().hashCode());
        result = prime * result + ((getMontoR() == null) ? 0 : getMontoR().hashCode());
        result = prime * result + ((getMontoStrR() == null) ? 0 : getMontoStrR().hashCode());
        result = prime * result + ((getMontoG() == null) ? 0 : getMontoG().hashCode());
        result = prime * result + ((getMontoStrG() == null) ? 0 : getMontoStrG().hashCode());
        return result;
    }
}