package mx.gob.sep.dgtec.repuce.model;

import java.util.Date;

public class CeIntegranteBaja {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.c_cct
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private Integer cCct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.c_sesion
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private Short cSesion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.csc_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private Integer cscIntegrante;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.paterno_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private String paternoIntegrante;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.materno_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private String maternoIntegrante;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.nombre_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private String nombreIntegrante;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.email_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private String emailIntegrante;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.tel_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private String telIntegrante;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.fch_baja
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private Date fchBaja;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.c_cargo
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private Integer cCargo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.c_niveleduc
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private Integer cNiveleduc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.genero
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private String genero;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.c_grado
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private Integer cGrado;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.c_nivel
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private Short cNivel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.c_calidad
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private Integer cCalidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.calidad_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private String calidadIntegrante;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.curp
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private String curp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.curp_valida
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private String curpValida;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_integrante_baja.identificacion
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    private Integer identificacion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.c_cct
     *
     * @return the value of ce_integrante_baja.c_cct
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public Integer getcCct() {
        return cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.c_cct
     *
     * @param cCct the value for ce_integrante_baja.c_cct
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setcCct(Integer cCct) {
        this.cCct = cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.c_sesion
     *
     * @return the value of ce_integrante_baja.c_sesion
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public Short getcSesion() {
        return cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.c_sesion
     *
     * @param cSesion the value for ce_integrante_baja.c_sesion
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setcSesion(Short cSesion) {
        this.cSesion = cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.csc_integrante
     *
     * @return the value of ce_integrante_baja.csc_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public Integer getCscIntegrante() {
        return cscIntegrante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.csc_integrante
     *
     * @param cscIntegrante the value for ce_integrante_baja.csc_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setCscIntegrante(Integer cscIntegrante) {
        this.cscIntegrante = cscIntegrante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.paterno_integrante
     *
     * @return the value of ce_integrante_baja.paterno_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public String getPaternoIntegrante() {
        return paternoIntegrante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.paterno_integrante
     *
     * @param paternoIntegrante the value for ce_integrante_baja.paterno_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setPaternoIntegrante(String paternoIntegrante) {
        this.paternoIntegrante = paternoIntegrante == null ? null : paternoIntegrante.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.materno_integrante
     *
     * @return the value of ce_integrante_baja.materno_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public String getMaternoIntegrante() {
        return maternoIntegrante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.materno_integrante
     *
     * @param maternoIntegrante the value for ce_integrante_baja.materno_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setMaternoIntegrante(String maternoIntegrante) {
        this.maternoIntegrante = maternoIntegrante == null ? null : maternoIntegrante.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.nombre_integrante
     *
     * @return the value of ce_integrante_baja.nombre_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public String getNombreIntegrante() {
        return nombreIntegrante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.nombre_integrante
     *
     * @param nombreIntegrante the value for ce_integrante_baja.nombre_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setNombreIntegrante(String nombreIntegrante) {
        this.nombreIntegrante = nombreIntegrante == null ? null : nombreIntegrante.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.email_integrante
     *
     * @return the value of ce_integrante_baja.email_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public String getEmailIntegrante() {
        return emailIntegrante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.email_integrante
     *
     * @param emailIntegrante the value for ce_integrante_baja.email_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setEmailIntegrante(String emailIntegrante) {
        this.emailIntegrante = emailIntegrante == null ? null : emailIntegrante.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.tel_integrante
     *
     * @return the value of ce_integrante_baja.tel_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public String getTelIntegrante() {
        return telIntegrante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.tel_integrante
     *
     * @param telIntegrante the value for ce_integrante_baja.tel_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setTelIntegrante(String telIntegrante) {
        this.telIntegrante = telIntegrante == null ? null : telIntegrante.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.fch_baja
     *
     * @return the value of ce_integrante_baja.fch_baja
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public Date getFchBaja() {
        return fchBaja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.fch_baja
     *
     * @param fchBaja the value for ce_integrante_baja.fch_baja
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setFchBaja(Date fchBaja) {
        this.fchBaja = fchBaja;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.c_cargo
     *
     * @return the value of ce_integrante_baja.c_cargo
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public Integer getcCargo() {
        return cCargo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.c_cargo
     *
     * @param cCargo the value for ce_integrante_baja.c_cargo
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setcCargo(Integer cCargo) {
        this.cCargo = cCargo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.c_niveleduc
     *
     * @return the value of ce_integrante_baja.c_niveleduc
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public Integer getcNiveleduc() {
        return cNiveleduc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.c_niveleduc
     *
     * @param cNiveleduc the value for ce_integrante_baja.c_niveleduc
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setcNiveleduc(Integer cNiveleduc) {
        this.cNiveleduc = cNiveleduc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.genero
     *
     * @return the value of ce_integrante_baja.genero
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public String getGenero() {
        return genero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.genero
     *
     * @param genero the value for ce_integrante_baja.genero
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setGenero(String genero) {
        this.genero = genero == null ? null : genero.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.c_grado
     *
     * @return the value of ce_integrante_baja.c_grado
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public Integer getcGrado() {
        return cGrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.c_grado
     *
     * @param cGrado the value for ce_integrante_baja.c_grado
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setcGrado(Integer cGrado) {
        this.cGrado = cGrado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.c_nivel
     *
     * @return the value of ce_integrante_baja.c_nivel
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public Short getcNivel() {
        return cNivel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.c_nivel
     *
     * @param cNivel the value for ce_integrante_baja.c_nivel
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setcNivel(Short cNivel) {
        this.cNivel = cNivel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.c_calidad
     *
     * @return the value of ce_integrante_baja.c_calidad
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public Integer getcCalidad() {
        return cCalidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.c_calidad
     *
     * @param cCalidad the value for ce_integrante_baja.c_calidad
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setcCalidad(Integer cCalidad) {
        this.cCalidad = cCalidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.calidad_integrante
     *
     * @return the value of ce_integrante_baja.calidad_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public String getCalidadIntegrante() {
        return calidadIntegrante;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.calidad_integrante
     *
     * @param calidadIntegrante the value for ce_integrante_baja.calidad_integrante
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setCalidadIntegrante(String calidadIntegrante) {
        this.calidadIntegrante = calidadIntegrante == null ? null : calidadIntegrante.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.curp
     *
     * @return the value of ce_integrante_baja.curp
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public String getCurp() {
        return curp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.curp
     *
     * @param curp the value for ce_integrante_baja.curp
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setCurp(String curp) {
        this.curp = curp == null ? null : curp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.curp_valida
     *
     * @return the value of ce_integrante_baja.curp_valida
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public String getCurpValida() {
        return curpValida;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.curp_valida
     *
     * @param curpValida the value for ce_integrante_baja.curp_valida
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setCurpValida(String curpValida) {
        this.curpValida = curpValida == null ? null : curpValida.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_integrante_baja.identificacion
     *
     * @return the value of ce_integrante_baja.identificacion
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public Integer getIdentificacion() {
        return identificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_integrante_baja.identificacion
     *
     * @param identificacion the value for ce_integrante_baja.identificacion
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    public void setIdentificacion(Integer identificacion) {
        this.identificacion = identificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_baja
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CeIntegranteBaja other = (CeIntegranteBaja) that;
        return (this.getcCct() == null ? other.getcCct() == null : this.getcCct().equals(other.getcCct()))
            && (this.getcSesion() == null ? other.getcSesion() == null : this.getcSesion().equals(other.getcSesion()))
            && (this.getCscIntegrante() == null ? other.getCscIntegrante() == null : this.getCscIntegrante().equals(other.getCscIntegrante()))
            && (this.getPaternoIntegrante() == null ? other.getPaternoIntegrante() == null : this.getPaternoIntegrante().equals(other.getPaternoIntegrante()))
            && (this.getMaternoIntegrante() == null ? other.getMaternoIntegrante() == null : this.getMaternoIntegrante().equals(other.getMaternoIntegrante()))
            && (this.getNombreIntegrante() == null ? other.getNombreIntegrante() == null : this.getNombreIntegrante().equals(other.getNombreIntegrante()))
            && (this.getEmailIntegrante() == null ? other.getEmailIntegrante() == null : this.getEmailIntegrante().equals(other.getEmailIntegrante()))
            && (this.getTelIntegrante() == null ? other.getTelIntegrante() == null : this.getTelIntegrante().equals(other.getTelIntegrante()))
            && (this.getFchBaja() == null ? other.getFchBaja() == null : this.getFchBaja().equals(other.getFchBaja()))
            && (this.getcCargo() == null ? other.getcCargo() == null : this.getcCargo().equals(other.getcCargo()))
            && (this.getcNiveleduc() == null ? other.getcNiveleduc() == null : this.getcNiveleduc().equals(other.getcNiveleduc()))
            && (this.getGenero() == null ? other.getGenero() == null : this.getGenero().equals(other.getGenero()))
            && (this.getcGrado() == null ? other.getcGrado() == null : this.getcGrado().equals(other.getcGrado()))
            && (this.getcNivel() == null ? other.getcNivel() == null : this.getcNivel().equals(other.getcNivel()))
            && (this.getcCalidad() == null ? other.getcCalidad() == null : this.getcCalidad().equals(other.getcCalidad()))
            && (this.getCalidadIntegrante() == null ? other.getCalidadIntegrante() == null : this.getCalidadIntegrante().equals(other.getCalidadIntegrante()))
            && (this.getCurp() == null ? other.getCurp() == null : this.getCurp().equals(other.getCurp()))
            && (this.getCurpValida() == null ? other.getCurpValida() == null : this.getCurpValida().equals(other.getCurpValida()))
            && (this.getIdentificacion() == null ? other.getIdentificacion() == null : this.getIdentificacion().equals(other.getIdentificacion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_integrante_baja
     *
     * @mbggenerated Tue Aug 11 14:00:56 CDT 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcCct() == null) ? 0 : getcCct().hashCode());
        result = prime * result + ((getcSesion() == null) ? 0 : getcSesion().hashCode());
        result = prime * result + ((getCscIntegrante() == null) ? 0 : getCscIntegrante().hashCode());
        result = prime * result + ((getPaternoIntegrante() == null) ? 0 : getPaternoIntegrante().hashCode());
        result = prime * result + ((getMaternoIntegrante() == null) ? 0 : getMaternoIntegrante().hashCode());
        result = prime * result + ((getNombreIntegrante() == null) ? 0 : getNombreIntegrante().hashCode());
        result = prime * result + ((getEmailIntegrante() == null) ? 0 : getEmailIntegrante().hashCode());
        result = prime * result + ((getTelIntegrante() == null) ? 0 : getTelIntegrante().hashCode());
        result = prime * result + ((getFchBaja() == null) ? 0 : getFchBaja().hashCode());
        result = prime * result + ((getcCargo() == null) ? 0 : getcCargo().hashCode());
        result = prime * result + ((getcNiveleduc() == null) ? 0 : getcNiveleduc().hashCode());
        result = prime * result + ((getGenero() == null) ? 0 : getGenero().hashCode());
        result = prime * result + ((getcGrado() == null) ? 0 : getcGrado().hashCode());
        result = prime * result + ((getcNivel() == null) ? 0 : getcNivel().hashCode());
        result = prime * result + ((getcCalidad() == null) ? 0 : getcCalidad().hashCode());
        result = prime * result + ((getCalidadIntegrante() == null) ? 0 : getCalidadIntegrante().hashCode());
        result = prime * result + ((getCurp() == null) ? 0 : getCurp().hashCode());
        result = prime * result + ((getCurpValida() == null) ? 0 : getCurpValida().hashCode());
        result = prime * result + ((getIdentificacion() == null) ? 0 : getIdentificacion().hashCode());
        return result;
    }
}