package mx.gob.sep.dgtec.repuce.model;

import java.util.Date;

public class CEntidad {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_entidad.id_entidadfed
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Short idEntidadfed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_entidad.nom_entidadfed
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String nomEntidadfed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_entidad.fch_ini_vigencia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Date fchIniVigencia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_entidad.status
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_entidad.id_usuario
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String idUsuario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_entidad.id_entidadfed
     *
     * @return the value of c_entidad.id_entidadfed
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Short getIdEntidadfed() {
        return idEntidadfed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_entidad.id_entidadfed
     *
     * @param idEntidadfed the value for c_entidad.id_entidadfed
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setIdEntidadfed(Short idEntidadfed) {
        this.idEntidadfed = idEntidadfed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_entidad.nom_entidadfed
     *
     * @return the value of c_entidad.nom_entidadfed
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getNomEntidadfed() {
        return nomEntidadfed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_entidad.nom_entidadfed
     *
     * @param nomEntidadfed the value for c_entidad.nom_entidadfed
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setNomEntidadfed(String nomEntidadfed) {
        this.nomEntidadfed = nomEntidadfed == null ? null : nomEntidadfed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_entidad.fch_ini_vigencia
     *
     * @return the value of c_entidad.fch_ini_vigencia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Date getFchIniVigencia() {
        return fchIniVigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_entidad.fch_ini_vigencia
     *
     * @param fchIniVigencia the value for c_entidad.fch_ini_vigencia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setFchIniVigencia(Date fchIniVigencia) {
        this.fchIniVigencia = fchIniVigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_entidad.status
     *
     * @return the value of c_entidad.status
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_entidad.status
     *
     * @param status the value for c_entidad.status
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_entidad.id_usuario
     *
     * @return the value of c_entidad.id_usuario
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getIdUsuario() {
        return idUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_entidad.id_usuario
     *
     * @param idUsuario the value for c_entidad.id_usuario
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario == null ? null : idUsuario.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CEntidad other = (CEntidad) that;
        return (this.getIdEntidadfed() == null ? other.getIdEntidadfed() == null : this.getIdEntidadfed().equals(other.getIdEntidadfed()))
            && (this.getNomEntidadfed() == null ? other.getNomEntidadfed() == null : this.getNomEntidadfed().equals(other.getNomEntidadfed()))
            && (this.getFchIniVigencia() == null ? other.getFchIniVigencia() == null : this.getFchIniVigencia().equals(other.getFchIniVigencia()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getIdUsuario() == null ? other.getIdUsuario() == null : this.getIdUsuario().equals(other.getIdUsuario()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_entidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdEntidadfed() == null) ? 0 : getIdEntidadfed().hashCode());
        result = prime * result + ((getNomEntidadfed() == null) ? 0 : getNomEntidadfed().hashCode());
        result = prime * result + ((getFchIniVigencia() == null) ? 0 : getFchIniVigencia().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getIdUsuario() == null) ? 0 : getIdUsuario().hashCode());
        return result;
    }
}