package mx.gob.sep.dgtec.repuce.model;

import java.math.BigDecimal;

public class CeRecursosPadres {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.c_cct
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private Integer cCct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.c_sesion
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private Short cSesion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.id_consecutivor
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private Short idConsecutivor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_r1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private BigDecimal montoR1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_str_r1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private String montoStrR1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_g1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private BigDecimal montoG1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_str_g1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private String montoStrG1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_g2
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private BigDecimal montoG2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_str_g2
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private String montoStrG2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_g3
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private BigDecimal montoG3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_str_g3
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private String montoStrG3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.otro
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private String otro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_g4
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private BigDecimal montoG4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_str_g4
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private String montoStrG4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.otro2
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private String otro2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_g5
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private BigDecimal montoG5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.monto_str_g5
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private String montoStrG5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ce_recursos_padres.otro3
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    private String otro3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.c_cct
     *
     * @return the value of ce_recursos_padres.c_cct
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public Integer getcCct() {
        return cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.c_cct
     *
     * @param cCct the value for ce_recursos_padres.c_cct
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setcCct(Integer cCct) {
        this.cCct = cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.c_sesion
     *
     * @return the value of ce_recursos_padres.c_sesion
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public Short getcSesion() {
        return cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.c_sesion
     *
     * @param cSesion the value for ce_recursos_padres.c_sesion
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setcSesion(Short cSesion) {
        this.cSesion = cSesion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.id_consecutivor
     *
     * @return the value of ce_recursos_padres.id_consecutivor
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public Short getIdConsecutivor() {
        return idConsecutivor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.id_consecutivor
     *
     * @param idConsecutivor the value for ce_recursos_padres.id_consecutivor
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setIdConsecutivor(Short idConsecutivor) {
        this.idConsecutivor = idConsecutivor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_r1
     *
     * @return the value of ce_recursos_padres.monto_r1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public BigDecimal getMontoR1() {
        return montoR1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_r1
     *
     * @param montoR1 the value for ce_recursos_padres.monto_r1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoR1(BigDecimal montoR1) {
        this.montoR1 = montoR1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_str_r1
     *
     * @return the value of ce_recursos_padres.monto_str_r1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public String getMontoStrR1() {
        return montoStrR1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_str_r1
     *
     * @param montoStrR1 the value for ce_recursos_padres.monto_str_r1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoStrR1(String montoStrR1) {
        this.montoStrR1 = montoStrR1 == null ? null : montoStrR1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_g1
     *
     * @return the value of ce_recursos_padres.monto_g1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public BigDecimal getMontoG1() {
        return montoG1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_g1
     *
     * @param montoG1 the value for ce_recursos_padres.monto_g1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoG1(BigDecimal montoG1) {
        this.montoG1 = montoG1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_str_g1
     *
     * @return the value of ce_recursos_padres.monto_str_g1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public String getMontoStrG1() {
        return montoStrG1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_str_g1
     *
     * @param montoStrG1 the value for ce_recursos_padres.monto_str_g1
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoStrG1(String montoStrG1) {
        this.montoStrG1 = montoStrG1 == null ? null : montoStrG1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_g2
     *
     * @return the value of ce_recursos_padres.monto_g2
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public BigDecimal getMontoG2() {
        return montoG2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_g2
     *
     * @param montoG2 the value for ce_recursos_padres.monto_g2
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoG2(BigDecimal montoG2) {
        this.montoG2 = montoG2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_str_g2
     *
     * @return the value of ce_recursos_padres.monto_str_g2
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public String getMontoStrG2() {
        return montoStrG2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_str_g2
     *
     * @param montoStrG2 the value for ce_recursos_padres.monto_str_g2
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoStrG2(String montoStrG2) {
        this.montoStrG2 = montoStrG2 == null ? null : montoStrG2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_g3
     *
     * @return the value of ce_recursos_padres.monto_g3
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public BigDecimal getMontoG3() {
        return montoG3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_g3
     *
     * @param montoG3 the value for ce_recursos_padres.monto_g3
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoG3(BigDecimal montoG3) {
        this.montoG3 = montoG3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_str_g3
     *
     * @return the value of ce_recursos_padres.monto_str_g3
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public String getMontoStrG3() {
        return montoStrG3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_str_g3
     *
     * @param montoStrG3 the value for ce_recursos_padres.monto_str_g3
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoStrG3(String montoStrG3) {
        this.montoStrG3 = montoStrG3 == null ? null : montoStrG3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.otro
     *
     * @return the value of ce_recursos_padres.otro
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public String getOtro() {
        return otro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.otro
     *
     * @param otro the value for ce_recursos_padres.otro
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setOtro(String otro) {
        this.otro = otro == null ? null : otro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_g4
     *
     * @return the value of ce_recursos_padres.monto_g4
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public BigDecimal getMontoG4() {
        return montoG4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_g4
     *
     * @param montoG4 the value for ce_recursos_padres.monto_g4
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoG4(BigDecimal montoG4) {
        this.montoG4 = montoG4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_str_g4
     *
     * @return the value of ce_recursos_padres.monto_str_g4
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public String getMontoStrG4() {
        return montoStrG4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_str_g4
     *
     * @param montoStrG4 the value for ce_recursos_padres.monto_str_g4
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoStrG4(String montoStrG4) {
        this.montoStrG4 = montoStrG4 == null ? null : montoStrG4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.otro2
     *
     * @return the value of ce_recursos_padres.otro2
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public String getOtro2() {
        return otro2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.otro2
     *
     * @param otro2 the value for ce_recursos_padres.otro2
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setOtro2(String otro2) {
        this.otro2 = otro2 == null ? null : otro2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_g5
     *
     * @return the value of ce_recursos_padres.monto_g5
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public BigDecimal getMontoG5() {
        return montoG5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_g5
     *
     * @param montoG5 the value for ce_recursos_padres.monto_g5
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoG5(BigDecimal montoG5) {
        this.montoG5 = montoG5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.monto_str_g5
     *
     * @return the value of ce_recursos_padres.monto_str_g5
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public String getMontoStrG5() {
        return montoStrG5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.monto_str_g5
     *
     * @param montoStrG5 the value for ce_recursos_padres.monto_str_g5
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setMontoStrG5(String montoStrG5) {
        this.montoStrG5 = montoStrG5 == null ? null : montoStrG5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ce_recursos_padres.otro3
     *
     * @return the value of ce_recursos_padres.otro3
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public String getOtro3() {
        return otro3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ce_recursos_padres.otro3
     *
     * @param otro3 the value for ce_recursos_padres.otro3
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    public void setOtro3(String otro3) {
        this.otro3 = otro3 == null ? null : otro3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recursos_padres
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CeRecursosPadres other = (CeRecursosPadres) that;
        return (this.getcCct() == null ? other.getcCct() == null : this.getcCct().equals(other.getcCct()))
            && (this.getcSesion() == null ? other.getcSesion() == null : this.getcSesion().equals(other.getcSesion()))
            && (this.getIdConsecutivor() == null ? other.getIdConsecutivor() == null : this.getIdConsecutivor().equals(other.getIdConsecutivor()))
            && (this.getMontoR1() == null ? other.getMontoR1() == null : this.getMontoR1().equals(other.getMontoR1()))
            && (this.getMontoStrR1() == null ? other.getMontoStrR1() == null : this.getMontoStrR1().equals(other.getMontoStrR1()))
            && (this.getMontoG1() == null ? other.getMontoG1() == null : this.getMontoG1().equals(other.getMontoG1()))
            && (this.getMontoStrG1() == null ? other.getMontoStrG1() == null : this.getMontoStrG1().equals(other.getMontoStrG1()))
            && (this.getMontoG2() == null ? other.getMontoG2() == null : this.getMontoG2().equals(other.getMontoG2()))
            && (this.getMontoStrG2() == null ? other.getMontoStrG2() == null : this.getMontoStrG2().equals(other.getMontoStrG2()))
            && (this.getMontoG3() == null ? other.getMontoG3() == null : this.getMontoG3().equals(other.getMontoG3()))
            && (this.getMontoStrG3() == null ? other.getMontoStrG3() == null : this.getMontoStrG3().equals(other.getMontoStrG3()))
            && (this.getOtro() == null ? other.getOtro() == null : this.getOtro().equals(other.getOtro()))
            && (this.getMontoG4() == null ? other.getMontoG4() == null : this.getMontoG4().equals(other.getMontoG4()))
            && (this.getMontoStrG4() == null ? other.getMontoStrG4() == null : this.getMontoStrG4().equals(other.getMontoStrG4()))
            && (this.getOtro2() == null ? other.getOtro2() == null : this.getOtro2().equals(other.getOtro2()))
            && (this.getMontoG5() == null ? other.getMontoG5() == null : this.getMontoG5().equals(other.getMontoG5()))
            && (this.getMontoStrG5() == null ? other.getMontoStrG5() == null : this.getMontoStrG5().equals(other.getMontoStrG5()))
            && (this.getOtro3() == null ? other.getOtro3() == null : this.getOtro3().equals(other.getOtro3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ce_recursos_padres
     *
     * @mbggenerated Thu Apr 21 18:09:22 CDT 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcCct() == null) ? 0 : getcCct().hashCode());
        result = prime * result + ((getcSesion() == null) ? 0 : getcSesion().hashCode());
        result = prime * result + ((getIdConsecutivor() == null) ? 0 : getIdConsecutivor().hashCode());
        result = prime * result + ((getMontoR1() == null) ? 0 : getMontoR1().hashCode());
        result = prime * result + ((getMontoStrR1() == null) ? 0 : getMontoStrR1().hashCode());
        result = prime * result + ((getMontoG1() == null) ? 0 : getMontoG1().hashCode());
        result = prime * result + ((getMontoStrG1() == null) ? 0 : getMontoStrG1().hashCode());
        result = prime * result + ((getMontoG2() == null) ? 0 : getMontoG2().hashCode());
        result = prime * result + ((getMontoStrG2() == null) ? 0 : getMontoStrG2().hashCode());
        result = prime * result + ((getMontoG3() == null) ? 0 : getMontoG3().hashCode());
        result = prime * result + ((getMontoStrG3() == null) ? 0 : getMontoStrG3().hashCode());
        result = prime * result + ((getOtro() == null) ? 0 : getOtro().hashCode());
        result = prime * result + ((getMontoG4() == null) ? 0 : getMontoG4().hashCode());
        result = prime * result + ((getMontoStrG4() == null) ? 0 : getMontoStrG4().hashCode());
        result = prime * result + ((getOtro2() == null) ? 0 : getOtro2().hashCode());
        result = prime * result + ((getMontoG5() == null) ? 0 : getMontoG5().hashCode());
        result = prime * result + ((getMontoStrG5() == null) ? 0 : getMontoStrG5().hashCode());
        result = prime * result + ((getOtro3() == null) ? 0 : getOtro3().hashCode());
        return result;
    }
}