package mx.gob.sep.dgtec.repuce.model;

import java.util.Date;

public class CPlaneacion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_planeacion.c_planeacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Short cPlaneacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_planeacion.nom_planeacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String nomPlaneacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_planeacion.fch_vigencia_ini
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Date fchVigenciaIni;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_planeacion.fch_vigencia_fin
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Date fchVigenciaFin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_planeacion.fch_sistema_ini
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Date fchSistemaIni;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_planeacion.fch_sistema_fin
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Date fchSistemaFin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_planeacion.d_vigencia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String dVigencia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_planeacion.c_planeacion
     *
     * @return the value of c_planeacion.c_planeacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Short getcPlaneacion() {
        return cPlaneacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_planeacion.c_planeacion
     *
     * @param cPlaneacion the value for c_planeacion.c_planeacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setcPlaneacion(Short cPlaneacion) {
        this.cPlaneacion = cPlaneacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_planeacion.nom_planeacion
     *
     * @return the value of c_planeacion.nom_planeacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getNomPlaneacion() {
        return nomPlaneacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_planeacion.nom_planeacion
     *
     * @param nomPlaneacion the value for c_planeacion.nom_planeacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setNomPlaneacion(String nomPlaneacion) {
        this.nomPlaneacion = nomPlaneacion == null ? null : nomPlaneacion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_planeacion.fch_vigencia_ini
     *
     * @return the value of c_planeacion.fch_vigencia_ini
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Date getFchVigenciaIni() {
        return fchVigenciaIni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_planeacion.fch_vigencia_ini
     *
     * @param fchVigenciaIni the value for c_planeacion.fch_vigencia_ini
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setFchVigenciaIni(Date fchVigenciaIni) {
        this.fchVigenciaIni = fchVigenciaIni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_planeacion.fch_vigencia_fin
     *
     * @return the value of c_planeacion.fch_vigencia_fin
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Date getFchVigenciaFin() {
        return fchVigenciaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_planeacion.fch_vigencia_fin
     *
     * @param fchVigenciaFin the value for c_planeacion.fch_vigencia_fin
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setFchVigenciaFin(Date fchVigenciaFin) {
        this.fchVigenciaFin = fchVigenciaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_planeacion.fch_sistema_ini
     *
     * @return the value of c_planeacion.fch_sistema_ini
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Date getFchSistemaIni() {
        return fchSistemaIni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_planeacion.fch_sistema_ini
     *
     * @param fchSistemaIni the value for c_planeacion.fch_sistema_ini
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setFchSistemaIni(Date fchSistemaIni) {
        this.fchSistemaIni = fchSistemaIni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_planeacion.fch_sistema_fin
     *
     * @return the value of c_planeacion.fch_sistema_fin
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Date getFchSistemaFin() {
        return fchSistemaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_planeacion.fch_sistema_fin
     *
     * @param fchSistemaFin the value for c_planeacion.fch_sistema_fin
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setFchSistemaFin(Date fchSistemaFin) {
        this.fchSistemaFin = fchSistemaFin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_planeacion.d_vigencia
     *
     * @return the value of c_planeacion.d_vigencia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getdVigencia() {
        return dVigencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_planeacion.d_vigencia
     *
     * @param dVigencia the value for c_planeacion.d_vigencia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setdVigencia(String dVigencia) {
        this.dVigencia = dVigencia == null ? null : dVigencia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_planeacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CPlaneacion other = (CPlaneacion) that;
        return (this.getcPlaneacion() == null ? other.getcPlaneacion() == null : this.getcPlaneacion().equals(other.getcPlaneacion()))
            && (this.getNomPlaneacion() == null ? other.getNomPlaneacion() == null : this.getNomPlaneacion().equals(other.getNomPlaneacion()))
            && (this.getFchVigenciaIni() == null ? other.getFchVigenciaIni() == null : this.getFchVigenciaIni().equals(other.getFchVigenciaIni()))
            && (this.getFchVigenciaFin() == null ? other.getFchVigenciaFin() == null : this.getFchVigenciaFin().equals(other.getFchVigenciaFin()))
            && (this.getFchSistemaIni() == null ? other.getFchSistemaIni() == null : this.getFchSistemaIni().equals(other.getFchSistemaIni()))
            && (this.getFchSistemaFin() == null ? other.getFchSistemaFin() == null : this.getFchSistemaFin().equals(other.getFchSistemaFin()))
            && (this.getdVigencia() == null ? other.getdVigencia() == null : this.getdVigencia().equals(other.getdVigencia()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_planeacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcPlaneacion() == null) ? 0 : getcPlaneacion().hashCode());
        result = prime * result + ((getNomPlaneacion() == null) ? 0 : getNomPlaneacion().hashCode());
        result = prime * result + ((getFchVigenciaIni() == null) ? 0 : getFchVigenciaIni().hashCode());
        result = prime * result + ((getFchVigenciaFin() == null) ? 0 : getFchVigenciaFin().hashCode());
        result = prime * result + ((getFchSistemaIni() == null) ? 0 : getFchSistemaIni().hashCode());
        result = prime * result + ((getFchSistemaFin() == null) ? 0 : getFchSistemaFin().hashCode());
        result = prime * result + ((getdVigencia() == null) ? 0 : getdVigencia().hashCode());
        return result;
    }
}