package mx.gob.sep.dgtec.repuce.model;

public class CPoblacionIndigena {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_poblacion_indigena.c_poblacion_indigena
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    private Short cPoblacionIndigena;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_poblacion_indigena.descrip_larga
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    private String descripLarga;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_poblacion_indigena.descrip_corta
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    private String descripCorta;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_poblacion_indigena.c_poblacion_indigena
     *
     * @return the value of c_poblacion_indigena.c_poblacion_indigena
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    public Short getcPoblacionIndigena() {
        return cPoblacionIndigena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_poblacion_indigena.c_poblacion_indigena
     *
     * @param cPoblacionIndigena the value for c_poblacion_indigena.c_poblacion_indigena
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    public void setcPoblacionIndigena(Short cPoblacionIndigena) {
        this.cPoblacionIndigena = cPoblacionIndigena;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_poblacion_indigena.descrip_larga
     *
     * @return the value of c_poblacion_indigena.descrip_larga
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    public String getDescripLarga() {
        return descripLarga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_poblacion_indigena.descrip_larga
     *
     * @param descripLarga the value for c_poblacion_indigena.descrip_larga
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    public void setDescripLarga(String descripLarga) {
        this.descripLarga = descripLarga == null ? null : descripLarga.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_poblacion_indigena.descrip_corta
     *
     * @return the value of c_poblacion_indigena.descrip_corta
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    public String getDescripCorta() {
        return descripCorta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_poblacion_indigena.descrip_corta
     *
     * @param descripCorta the value for c_poblacion_indigena.descrip_corta
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    public void setDescripCorta(String descripCorta) {
        this.descripCorta = descripCorta == null ? null : descripCorta.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_poblacion_indigena
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CPoblacionIndigena other = (CPoblacionIndigena) that;
        return (this.getcPoblacionIndigena() == null ? other.getcPoblacionIndigena() == null : this.getcPoblacionIndigena().equals(other.getcPoblacionIndigena()))
            && (this.getDescripLarga() == null ? other.getDescripLarga() == null : this.getDescripLarga().equals(other.getDescripLarga()))
            && (this.getDescripCorta() == null ? other.getDescripCorta() == null : this.getDescripCorta().equals(other.getDescripCorta()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_poblacion_indigena
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcPoblacionIndigena() == null) ? 0 : getcPoblacionIndigena().hashCode());
        result = prime * result + ((getDescripLarga() == null) ? 0 : getDescripLarga().hashCode());
        result = prime * result + ((getDescripCorta() == null) ? 0 : getDescripCorta().hashCode());
        return result;
    }
}