package mx.gob.sep.dgtec.repuce.model;

public class CTipoDiagnosticoCom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_tipo_diagnostico_com.c_tipo_diagnostico_com
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    private Short cTipoDiagnosticoCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_tipo_diagnostico_com.nom_tipo_diag_comunitario
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    private String nomTipoDiagComunitario;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_tipo_diagnostico_com.c_tipo_diagnostico_com
     *
     * @return the value of c_tipo_diagnostico_com.c_tipo_diagnostico_com
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    public Short getcTipoDiagnosticoCom() {
        return cTipoDiagnosticoCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_tipo_diagnostico_com.c_tipo_diagnostico_com
     *
     * @param cTipoDiagnosticoCom the value for c_tipo_diagnostico_com.c_tipo_diagnostico_com
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    public void setcTipoDiagnosticoCom(Short cTipoDiagnosticoCom) {
        this.cTipoDiagnosticoCom = cTipoDiagnosticoCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_tipo_diagnostico_com.nom_tipo_diag_comunitario
     *
     * @return the value of c_tipo_diagnostico_com.nom_tipo_diag_comunitario
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    public String getNomTipoDiagComunitario() {
        return nomTipoDiagComunitario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_tipo_diagnostico_com.nom_tipo_diag_comunitario
     *
     * @param nomTipoDiagComunitario the value for c_tipo_diagnostico_com.nom_tipo_diag_comunitario
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    public void setNomTipoDiagComunitario(String nomTipoDiagComunitario) {
        this.nomTipoDiagComunitario = nomTipoDiagComunitario == null ? null : nomTipoDiagComunitario.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_diagnostico_com
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CTipoDiagnosticoCom other = (CTipoDiagnosticoCom) that;
        return (this.getcTipoDiagnosticoCom() == null ? other.getcTipoDiagnosticoCom() == null : this.getcTipoDiagnosticoCom().equals(other.getcTipoDiagnosticoCom()))
            && (this.getNomTipoDiagComunitario() == null ? other.getNomTipoDiagComunitario() == null : this.getNomTipoDiagComunitario().equals(other.getNomTipoDiagComunitario()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_tipo_diagnostico_com
     *
     * @mbggenerated Tue Oct 15 10:17:54 CDT 2013
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcTipoDiagnosticoCom() == null) ? 0 : getcTipoDiagnosticoCom().hashCode());
        result = prime * result + ((getNomTipoDiagComunitario() == null) ? 0 : getNomTipoDiagComunitario().hashCode());
        return result;
    }
}