package mx.gob.sep.dgtec.repuce.model;

public class EncuestaCct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encuesta_cct.c_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Integer cCct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encuesta_cct.motivo
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Short motivo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column encuesta_cct.otro_motivo
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String otroMotivo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encuesta_cct.c_cct
     *
     * @return the value of encuesta_cct.c_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Integer getcCct() {
        return cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encuesta_cct.c_cct
     *
     * @param cCct the value for encuesta_cct.c_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setcCct(Integer cCct) {
        this.cCct = cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encuesta_cct.motivo
     *
     * @return the value of encuesta_cct.motivo
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Short getMotivo() {
        return motivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encuesta_cct.motivo
     *
     * @param motivo the value for encuesta_cct.motivo
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setMotivo(Short motivo) {
        this.motivo = motivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column encuesta_cct.otro_motivo
     *
     * @return the value of encuesta_cct.otro_motivo
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getOtroMotivo() {
        return otroMotivo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column encuesta_cct.otro_motivo
     *
     * @param otroMotivo the value for encuesta_cct.otro_motivo
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setOtroMotivo(String otroMotivo) {
        this.otroMotivo = otroMotivo == null ? null : otroMotivo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encuesta_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EncuestaCct other = (EncuestaCct) that;
        return (this.getcCct() == null ? other.getcCct() == null : this.getcCct().equals(other.getcCct()))
            && (this.getMotivo() == null ? other.getMotivo() == null : this.getMotivo().equals(other.getMotivo()))
            && (this.getOtroMotivo() == null ? other.getOtroMotivo() == null : this.getOtroMotivo().equals(other.getOtroMotivo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table encuesta_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcCct() == null) ? 0 : getcCct().hashCode());
        result = prime * result + ((getMotivo() == null) ? 0 : getMotivo().hashCode());
        result = prime * result + ((getOtroMotivo() == null) ? 0 : getOtroMotivo().hashCode());
        return result;
    }
}