package mx.gob.sep.dgtec.repuce.model;

public class UbicacionCct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.c_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Integer cCct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.id_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Integer idLocalidad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.id_municipio
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Integer idMunicipio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.id_entidadfed
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Short idEntidadfed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.domicilio
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String domicilio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.nom_colonia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String nomColonia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.cp
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String cp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.entre_calle
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String entreCalle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.y_calle
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String yCalle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.cve_sector
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String cveSector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.cct_sector
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String cctSector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.zona_escolar
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String zonaEscolar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.cct_zona_escolar
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String cctZonaEscolar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.ambito
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String ambito;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.cve_colonia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String cveColonia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.longitud
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String longitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.latitud
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String latitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.altitud
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String altitud;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.indice_marginacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private Short indiceMarginacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ubicacion_cct.gdo_marginacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    private String gdoMarginacion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.c_cct
     *
     * @return the value of ubicacion_cct.c_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Integer getcCct() {
        return cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.c_cct
     *
     * @param cCct the value for ubicacion_cct.c_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setcCct(Integer cCct) {
        this.cCct = cCct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.id_localidad
     *
     * @return the value of ubicacion_cct.id_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Integer getIdLocalidad() {
        return idLocalidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.id_localidad
     *
     * @param idLocalidad the value for ubicacion_cct.id_localidad
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setIdLocalidad(Integer idLocalidad) {
        this.idLocalidad = idLocalidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.id_municipio
     *
     * @return the value of ubicacion_cct.id_municipio
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Integer getIdMunicipio() {
        return idMunicipio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.id_municipio
     *
     * @param idMunicipio the value for ubicacion_cct.id_municipio
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.id_entidadfed
     *
     * @return the value of ubicacion_cct.id_entidadfed
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Short getIdEntidadfed() {
        return idEntidadfed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.id_entidadfed
     *
     * @param idEntidadfed the value for ubicacion_cct.id_entidadfed
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setIdEntidadfed(Short idEntidadfed) {
        this.idEntidadfed = idEntidadfed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.domicilio
     *
     * @return the value of ubicacion_cct.domicilio
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getDomicilio() {
        return domicilio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.domicilio
     *
     * @param domicilio the value for ubicacion_cct.domicilio
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio == null ? null : domicilio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.nom_colonia
     *
     * @return the value of ubicacion_cct.nom_colonia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getNomColonia() {
        return nomColonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.nom_colonia
     *
     * @param nomColonia the value for ubicacion_cct.nom_colonia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setNomColonia(String nomColonia) {
        this.nomColonia = nomColonia == null ? null : nomColonia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.cp
     *
     * @return the value of ubicacion_cct.cp
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getCp() {
        return cp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.cp
     *
     * @param cp the value for ubicacion_cct.cp
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setCp(String cp) {
        this.cp = cp == null ? null : cp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.entre_calle
     *
     * @return the value of ubicacion_cct.entre_calle
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getEntreCalle() {
        return entreCalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.entre_calle
     *
     * @param entreCalle the value for ubicacion_cct.entre_calle
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setEntreCalle(String entreCalle) {
        this.entreCalle = entreCalle == null ? null : entreCalle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.y_calle
     *
     * @return the value of ubicacion_cct.y_calle
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getyCalle() {
        return yCalle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.y_calle
     *
     * @param yCalle the value for ubicacion_cct.y_calle
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setyCalle(String yCalle) {
        this.yCalle = yCalle == null ? null : yCalle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.cve_sector
     *
     * @return the value of ubicacion_cct.cve_sector
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getCveSector() {
        return cveSector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.cve_sector
     *
     * @param cveSector the value for ubicacion_cct.cve_sector
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setCveSector(String cveSector) {
        this.cveSector = cveSector == null ? null : cveSector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.cct_sector
     *
     * @return the value of ubicacion_cct.cct_sector
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getCctSector() {
        return cctSector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.cct_sector
     *
     * @param cctSector the value for ubicacion_cct.cct_sector
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setCctSector(String cctSector) {
        this.cctSector = cctSector == null ? null : cctSector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.zona_escolar
     *
     * @return the value of ubicacion_cct.zona_escolar
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getZonaEscolar() {
        return zonaEscolar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.zona_escolar
     *
     * @param zonaEscolar the value for ubicacion_cct.zona_escolar
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setZonaEscolar(String zonaEscolar) {
        this.zonaEscolar = zonaEscolar == null ? null : zonaEscolar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.cct_zona_escolar
     *
     * @return the value of ubicacion_cct.cct_zona_escolar
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getCctZonaEscolar() {
        return cctZonaEscolar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.cct_zona_escolar
     *
     * @param cctZonaEscolar the value for ubicacion_cct.cct_zona_escolar
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setCctZonaEscolar(String cctZonaEscolar) {
        this.cctZonaEscolar = cctZonaEscolar == null ? null : cctZonaEscolar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.ambito
     *
     * @return the value of ubicacion_cct.ambito
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getAmbito() {
        return ambito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.ambito
     *
     * @param ambito the value for ubicacion_cct.ambito
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setAmbito(String ambito) {
        this.ambito = ambito == null ? null : ambito.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.cve_colonia
     *
     * @return the value of ubicacion_cct.cve_colonia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getCveColonia() {
        return cveColonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.cve_colonia
     *
     * @param cveColonia the value for ubicacion_cct.cve_colonia
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setCveColonia(String cveColonia) {
        this.cveColonia = cveColonia == null ? null : cveColonia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.longitud
     *
     * @return the value of ubicacion_cct.longitud
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getLongitud() {
        return longitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.longitud
     *
     * @param longitud the value for ubicacion_cct.longitud
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setLongitud(String longitud) {
        this.longitud = longitud == null ? null : longitud.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.latitud
     *
     * @return the value of ubicacion_cct.latitud
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getLatitud() {
        return latitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.latitud
     *
     * @param latitud the value for ubicacion_cct.latitud
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setLatitud(String latitud) {
        this.latitud = latitud == null ? null : latitud.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.altitud
     *
     * @return the value of ubicacion_cct.altitud
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getAltitud() {
        return altitud;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.altitud
     *
     * @param altitud the value for ubicacion_cct.altitud
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setAltitud(String altitud) {
        this.altitud = altitud == null ? null : altitud.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.indice_marginacion
     *
     * @return the value of ubicacion_cct.indice_marginacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public Short getIndiceMarginacion() {
        return indiceMarginacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.indice_marginacion
     *
     * @param indiceMarginacion the value for ubicacion_cct.indice_marginacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setIndiceMarginacion(Short indiceMarginacion) {
        this.indiceMarginacion = indiceMarginacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ubicacion_cct.gdo_marginacion
     *
     * @return the value of ubicacion_cct.gdo_marginacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public String getGdoMarginacion() {
        return gdoMarginacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ubicacion_cct.gdo_marginacion
     *
     * @param gdoMarginacion the value for ubicacion_cct.gdo_marginacion
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    public void setGdoMarginacion(String gdoMarginacion) {
        this.gdoMarginacion = gdoMarginacion == null ? null : gdoMarginacion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ubicacion_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UbicacionCct other = (UbicacionCct) that;
        return (this.getcCct() == null ? other.getcCct() == null : this.getcCct().equals(other.getcCct()))
            && (this.getIdLocalidad() == null ? other.getIdLocalidad() == null : this.getIdLocalidad().equals(other.getIdLocalidad()))
            && (this.getIdMunicipio() == null ? other.getIdMunicipio() == null : this.getIdMunicipio().equals(other.getIdMunicipio()))
            && (this.getIdEntidadfed() == null ? other.getIdEntidadfed() == null : this.getIdEntidadfed().equals(other.getIdEntidadfed()))
            && (this.getDomicilio() == null ? other.getDomicilio() == null : this.getDomicilio().equals(other.getDomicilio()))
            && (this.getNomColonia() == null ? other.getNomColonia() == null : this.getNomColonia().equals(other.getNomColonia()))
            && (this.getCp() == null ? other.getCp() == null : this.getCp().equals(other.getCp()))
            && (this.getEntreCalle() == null ? other.getEntreCalle() == null : this.getEntreCalle().equals(other.getEntreCalle()))
            && (this.getyCalle() == null ? other.getyCalle() == null : this.getyCalle().equals(other.getyCalle()))
            && (this.getCveSector() == null ? other.getCveSector() == null : this.getCveSector().equals(other.getCveSector()))
            && (this.getCctSector() == null ? other.getCctSector() == null : this.getCctSector().equals(other.getCctSector()))
            && (this.getZonaEscolar() == null ? other.getZonaEscolar() == null : this.getZonaEscolar().equals(other.getZonaEscolar()))
            && (this.getCctZonaEscolar() == null ? other.getCctZonaEscolar() == null : this.getCctZonaEscolar().equals(other.getCctZonaEscolar()))
            && (this.getAmbito() == null ? other.getAmbito() == null : this.getAmbito().equals(other.getAmbito()))
            && (this.getCveColonia() == null ? other.getCveColonia() == null : this.getCveColonia().equals(other.getCveColonia()))
            && (this.getLongitud() == null ? other.getLongitud() == null : this.getLongitud().equals(other.getLongitud()))
            && (this.getLatitud() == null ? other.getLatitud() == null : this.getLatitud().equals(other.getLatitud()))
            && (this.getAltitud() == null ? other.getAltitud() == null : this.getAltitud().equals(other.getAltitud()))
            && (this.getIndiceMarginacion() == null ? other.getIndiceMarginacion() == null : this.getIndiceMarginacion().equals(other.getIndiceMarginacion()))
            && (this.getGdoMarginacion() == null ? other.getGdoMarginacion() == null : this.getGdoMarginacion().equals(other.getGdoMarginacion()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ubicacion_cct
     *
     * @mbggenerated Mon Oct 29 17:47:29 CST 2012
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcCct() == null) ? 0 : getcCct().hashCode());
        result = prime * result + ((getIdLocalidad() == null) ? 0 : getIdLocalidad().hashCode());
        result = prime * result + ((getIdMunicipio() == null) ? 0 : getIdMunicipio().hashCode());
        result = prime * result + ((getIdEntidadfed() == null) ? 0 : getIdEntidadfed().hashCode());
        result = prime * result + ((getDomicilio() == null) ? 0 : getDomicilio().hashCode());
        result = prime * result + ((getNomColonia() == null) ? 0 : getNomColonia().hashCode());
        result = prime * result + ((getCp() == null) ? 0 : getCp().hashCode());
        result = prime * result + ((getEntreCalle() == null) ? 0 : getEntreCalle().hashCode());
        result = prime * result + ((getyCalle() == null) ? 0 : getyCalle().hashCode());
        result = prime * result + ((getCveSector() == null) ? 0 : getCveSector().hashCode());
        result = prime * result + ((getCctSector() == null) ? 0 : getCctSector().hashCode());
        result = prime * result + ((getZonaEscolar() == null) ? 0 : getZonaEscolar().hashCode());
        result = prime * result + ((getCctZonaEscolar() == null) ? 0 : getCctZonaEscolar().hashCode());
        result = prime * result + ((getAmbito() == null) ? 0 : getAmbito().hashCode());
        result = prime * result + ((getCveColonia() == null) ? 0 : getCveColonia().hashCode());
        result = prime * result + ((getLongitud() == null) ? 0 : getLongitud().hashCode());
        result = prime * result + ((getLatitud() == null) ? 0 : getLatitud().hashCode());
        result = prime * result + ((getAltitud() == null) ? 0 : getAltitud().hashCode());
        result = prime * result + ((getIndiceMarginacion() == null) ? 0 : getIndiceMarginacion().hashCode());
        result = prime * result + ((getGdoMarginacion() == null) ? 0 : getGdoMarginacion().hashCode());
        return result;
    }
}